### ISSUE TITLE
Crash during startup

### ISSUE THREAD

**Issue by cryorooster** [nosmokingbandit/Watcher3#1]
Starting up a fresh download of version 9a36a0b7ffab59e54add73bb67db15a9440fb540 on windows with python version 
`3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)]`
using
`py -3 watcher.py`
results in following crash:

> <.....>\Watcher3-master\lib\fuzzywuzzy\fuzz.py:35: UserWarning: Usin
> g slow pure-python SequenceMatcher. Install python-Levenshtein to remove this wa
> rning
>   warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levensht
> ein to remove this warning')
> Config file found, merging any new options.
> Database found.
> Traceback (most recent call last):
>   File "watcher.py", line 123, in <module>
>     root = cherrypy.tree.mount(App(),
>   File "<.....>\Watcher3-master\core\app.py", line 35, in __init__
>     scheduler.AutoUpdateCheck.update_check()
>   File "<.....>\Watcher3-master\core\scheduler.py", line 75, in upda
> te_check
>     ver = version.Version()
>   File "<.....>\Watcher3-master\core\version.py", line 28, in __init
> __
>     self.manager = ZipUpdater()
>   File "<.....>\Watcher3-master\core\version.py", line 254, in __ini
> t__
>     core.CURRENT_HASH = self.current_hash.decode('utf-8')
> AttributeError: 'str' object has no attribute 'decode'

Log above is from a repeated startup where a default config file was found that was created by a previous startup crashing with the same error.

Is 3.4 python just to old that is has no "decode" function on every string object? I could not find any other version requirements other than "3"

**Comment by nosmokingbandit** [comment]
The string class in all python 3 version has a decode method since all strings are now unicode and bytes are treated as actual bytes rather than strings like python 2. If it sounds confusing it is.

What is weird is that I had added that line right before announcing this repo because Git was giving me a bytestring for the hash.

I'm checking into it now.

**Comment by nosmokingbandit** [comment]
Commit 59d711dc71b694d6ab144138e63dd3b859f3a44d should fix this, let me know.

There was a problem with updating via zip that I needed to address, but Git only allows so many requests per ip per hour, so I had to take a quick break and wait them out.

**Comment by OldMike** [comment]
Hi,

Just cloned and got anotehr error.

`python3 -V
Python 3.4.2`

`/usr/bin/python3 /opt/Watcher3/watcher.py --port 2932
/opt/Watcher3/lib/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
Traceback (most recent call last):
  File "/opt/Watcher3/watcher.py", line 30, in <module>
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'
`

**Comment by cryorooster** [comment]
Nice, startup works now in 59d711dc71b694d6ab144138e63dd3b859f3a44d. Importing the backup from watcher(1) also worked successfully.
