### ISSUE TITLE
[Idea] Scheduled Events Page

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#103]
You've recently built the event scheduler to enable better tracking of events.

Can we have a page to display what time these will next run / maybe a tunable to allow custom timings for things to kick off?

**Comment by nosmokingbandit** [comment]
I've been thinking about something like a system page that shows scheduled tasks, watcher directory size, cpu/ram usage, etc. I can't remember why I stopped working on that, but I'll put it on my list so I don't forget.

Modifying execution time for scheduled tasks might not be too difficult, but I'll get the simple stuff done first.

**Comment by jaketame** [comment]
This is done so closing.
