### ISSUE TITLE
Error on directory import

### ISSUE THREAD

**Issue by Plude** [nosmokingbandit/Watcher3#105]
When i tried to import from directory i got the following error: 

> Traceback (most recent call last):
  File "/opt/Watcher3/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/opt/Watcher3/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/Watcher3/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/Watcher3/core/app.py", line 110, in library
    file_list = [i for i in os.listdir(start_dir) if os.path.isdir(os.path.join(start_dir, i)) and not i.startswith('.')]
FileNotFoundError: [Errno 2] No such file or directory: '/home/watcher'

The user "watcher" on my Debian system does not have a home folder so this mean that there are no exception catching for this as the code only catch PermissionError.

To fix this i changed the code in core/app.py on line 111 to:
`except (PermissionError, FileNotFoundError) as e:`

This made it possible to import with the directory method again.

**Comment by nosmokingbandit** [comment]
7c1faf18f086237250c144a00b6df3d196c152e1

I just changed it to catch all exceptions -- if anything goes wrong the dir is unusable anyway.
