### ISSUE TITLE
Not all movies from IMDb watchlist imported

### ISSUE THREAD

**Issue by theotherp** [nosmokingbandit/Watcher3#113]
I have 84 movies in my IMDb watchlist but watcher has only 33 imported. The RSS sync is apparently executed every hour. The log doesn't say anything.

Please let me know how I can provide better infos.

**Comment by nosmokingbandit** [comment]
Go to watcher/core/rss and delete the file `imdb` (NOT `imdb.py`) and see what happens next time it runs.

**Comment by theotherp** [comment]
Woah, sorry for the late response. I just had this problem again, googled for it, found this issue, did what you said. It solved the problem. I took a look at who originally posted this issue and behold, it was me!

Anyway, as I said, deleting the file fixed it. Cheers.

**Comment by nosmokingbandit** [comment]
I'm going through a lot of the scheduler functions and making a bit more sense of them. I'll fix this so it doesn't crop up again.
