### ISSUE TITLE
Torrentapi tokens expire but are not renewed

### ISSUE THREAD

**Issue by iskarian** [nosmokingbandit/Watcher3#114]
The torrentapi tokens used by the Rarbg indexer expire after some time. The [api docs](https://torrentapi.org/apidocs_v2.txt) indicate that the tokens expire after 15 minutes (though in my testing seem to last longer than that). It's not documented in the docs, but this is the response when using an expired token:

`{"error":"Invalid token. Use get_token for a new one!","error_code":4}`

It would probably be easiest just to store a timeout for the token and get a new one if the stored token is more than 15 minutes old.

**Comment by iskarian** [comment]
I can submit a PR for it if you'd like.

**Comment by iskarian** [comment]
Looks like that fixed it.

**Comment by nosmokingbandit** [comment]
I forgot to post here after pushing that update, sorry.

I clearly remember writing this once before, but apparently I didn't. Oh well, as long as everything works now I'm happy.
