### ISSUE TITLE
Auto Start in Ubuntu

### ISSUE THREAD

**Issue by MaDTaZ** [nosmokingbandit/Watcher3#115]
Hey 

I was trying to get this to work and wasnt able to get it to autostart.  Can anyone help me with this

**Comment by nosmokingbandit** [comment]
I use Debian, which should be identical to Ubuntu as far as systemd goes.

Open a terminal and run 

```
wget https://github.com/nosmokingbandit/Watcher3/blob/master/run%20scripts/systemd.init

nano systemd.init
```

Make sure the line that starts with `ExecStart=` points toward your python3 binary and your Watcher script and add whatever other startup arguments you want. Save with `ctrl-o`, `enter`, `ctrl-x`.

Then move the script to the correct location:

```
sudo mv systemd.init /etc/systemd/system/watcher.service

```

To start it run `sudo systemctl start watcher` and to make it start automatically on boot run `sudo systemctl enable watcher`

**Comment by MaDTaZ** [comment]
Thank you for the instruction 
This is the error I am getting when I try to start it

Aug 13 09:52:49 MaDTaZ-DarKNeT python3[22904]: Traceback (most recent call last):
Aug 13 09:52:49 MaDTaZ-DarKNeT python3[22904]:   File "/opt/watcher/watcher3/watcher.py", line 85, in <module>
Aug 13 09:52:49 MaDTaZ-DarKNeT python3[22904]:     conf.merge_new_options()
Aug 13 09:52:49 MaDTaZ-DarKNeT python3[22904]:   File "/opt/watcher/watcher3/core/config.py", line 124, in merge_new_optio
Aug 13 09:52:49 MaDTaZ-DarKNeT python3[22904]:     with open(self.file, 'w') as f:
Aug 13 09:52:49 MaDTaZ-DarKNeT python3[22904]: PermissionError: [Errno 13] Permission denied: '/opt/watcher/watcher3/confi
Aug 13 09:52:49 MaDTaZ-DarKNeT systemd[1]: watcher.service: Control process exited, code=exited status=1
Aug 13 09:52:49 MaDTaZ-DarKNeT systemd[1]: Failed to start Watcher Daemon.
Aug 13 09:52:49 MaDTaZ-DarKNeT systemd[1]: watcher.service: Unit entered failed state.
Aug 13 09:52:49 MaDTaZ-DarKNeT systemd[1]: watcher.service: Failed with result 'exit-code'.

**Comment by MaDTaZ** [comment]
Hey 

Thank you figured it out it was the permission when starting the service fixed those and everything worked.

Much Appreciated the help
