### ISSUE TITLE
NZBGet Post-processing Error (Seems related to #10)

### ISSUE THREAD

**Issue by DrMarf** [nosmokingbandit/Watcher3#12]
(I apologize first time submitting an issue so I hope I have everything you need.)
Here is my post processing log:

INFO 2017-04-07 10:24:53,620 core.postprocessing.POST: #################################
INFO 2017-04-07 10:24:53,620 core.postprocessing.POST: Post-processing request received.
INFO 2017-04-07 10:24:53,620 core.postprocessing.POST: #################################
INFO 2017-04-07 10:24:53,621 core.postprocessing.get_movie_file: Finding movie file.
INFO 2017-04-07 10:24:53,621 core.postprocessing.get_movie_file: Post-processing file /share/Download/nzbget/dst/Watcher/<removed>/<removed>.mkv.
INFO 2017-04-07 10:24:53,621 core.postprocessing.POST: Parsing release name for information.
INFO 2017-04-07 10:24:53,621 core.library.parse_filename: Parsing /share/Download/nzbget/dst/Watcher/<removed>/<removed>.mkv for movie information.
INFO 2017-04-07 10:24:53,622 core.library.parse_filename: Found {'episode': 94, 'container': 'mkv', 'title': '<removed>', 'episodeName': '<removed>'} in filename.
INFO 2017-04-07 10:24:53,623 core.postprocessing.POST: Gathering release information.
INFO 2017-04-07 10:24:53,623 core.postprocessing.get_movie_info: Searching local database for guid.
INFO 2017-04-07 10:24:53,623 core.sqldb.get_single_search_result: Retrieving search result details for http://localhost:5075/getnzb?apikey=<removed>.
INFO 2017-04-07 10:24:53,625 core.postprocessing.get_movie_info: Searchresult found by guid.
INFO 2017-04-07 10:24:53,625 core.postprocessing.get_movie_info: Searching local database by imdbid.
INFO 2017-04-07 10:24:53,625 core.sqldb.get_movie_details: Retrieving details for tt<removed>.
INFO 2017-04-07 10:24:53,627 core.postprocessing.get_movie_info: Movie data found locally by imdbid.
INFO 2017-04-07 10:24:53,628 core.postprocessing.POST: Post-processing as Complete.
INFO 2017-04-07 10:24:53,628 core.postprocessing.complete: Marking guid as Finished.
INFO 2017-04-07 10:24:53,628 core.library.searchresults: Marking guid http_//localhost_5075/getnzb_apikey=<removed> as Finished.
INFO 2017-04-07 10:24:53,630 core.library.searchresults: Guid http_//localhost_5075/getnzb_apikey=<removed> not found in SEARCHRESULTS, attempting to create entry.
ERROR 2017-04-07 10:24:53,630 cherrypy.error.139854216156888.error: [07/Apr/2017:10:24:53] HTTP 
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/core/postprocessing.py", line 102, in POST
    response = self.complete(data)
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/core/postprocessing.py", line 364, in complete
    if self.update.searchresults(data['guid'], 'Finished', movie_info=data):
  File "/share/CACHEDEV1_DATA/.qpkg/watcher3/core/library.py", line 639, in searchresults
    search_result = searchresults.generate_simulacrum(movie_info)
TypeError: 'staticmethod' object is not callable
INFO 2017-04-07 10:24:53,631 cherrypy.error.139854216156888.error: [07/Apr/2017:10:24:53] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  ACCEPT-ENCODING: identity
  HOST: localhost:9090
  CONNECTION: close
  USER-AGENT: Mozilla/5.0
  Content-Type: application/x-www-form-urlencoded
  Content-Length: 307

**Comment by nosmokingbandit** [comment]
This is the same as #10. Try again after commit 3e63e1f6270dca338b16ca47b86b6e6d7a235689

**Comment by DrMarf** [comment]
Thanks. I wasn't 100% sure and hoped a new thread would keep it cleaner.
