### ISSUE TITLE
Rename file and move folder

### ISSUE THREAD

**Issue by trackermb** [nosmokingbandit/Watcher3#121]
Hi there been playing with Watcher3 for a few days now and have noticed that I can only get it to either rename file or movie file to a renamed folder.  Is it possible to move to named folder and rename the file during post processing?

eg A Movie (2017)/A Movie (2017).mkv
instead of A Movie (2017)/A.Movie.2017.5.1.mkv

This feature may already be there and I've just missed it so any help would be great
Thanks

---
Edited by @nosmokingbandit
Please don't post release titles.

**Comment by nosmokingbandit** [comment]
e8ef64a1c026b30768fa809b43b6604c9b824c6d may or may not fix this for you. On my main server everything has been working fine but I did find a few bugs when running a few tasks on my testing server.

If this doesn't resolve anything send me your logs and I'll see what is going on.

`watchernzb@gmail.com`
