### ISSUE TITLE
Currently will not start

### ISSUE THREAD

**Issue by DraZtiK** [nosmokingbandit/Watcher3#122]
Any help would be greatly appreciated! 

`hello@apollo:/usr/local/sbin/Watcher3$ /usr/bin/python3 /usr/local/sbin/Watcher3/watcher.py --daemon --conf /mnt/h/linux/watcher/watcher.cfg --log /mnt/h/linux/watcher/ --db /mnt/h/linux/watcher/watcher.sqlite --plugins /mnt/h/linux/watcher/plugins
Connected to database sqlite:////mnt/h/linux/watcher/watcher.sqlite
Database update required. This may take some time.
Backing up database to /usr/local/sbin/Watcher3/db.
Executing database update 2
Executing database update 3
Config file found, merging any new options.

Traceback (most recent call last):
  File "/usr/local/sbin/Watcher3/watcher.py", line 85, in <module>
    conf.merge_new_options()
  File "/usr/local/sbin/Watcher3/core/config.py", line 106, in merge_new_options
    config = json.load(f)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by nosmokingbandit** [comment]
Something went wrong with your config file. Without seeing your config it is hard to know what happened. If you want, go through your config and remove any info you don't want me to see (api keys, etc) and email it to `watchernzb@gmail.com` so I can see what went wrong.

**Comment by DraZtiK** [comment]
You were correct. My cfg was empty. Not sure what killed it though.

**Comment by KingCalvin** [comment]
I also have this problem, my error messages are similar although I tried starting Watcher3 with both python 3.4 (my original setup which had worked well for months) and 3.6 (testing if my python version was the problem) to no avail.  My config file is also empty.
