### ISSUE TITLE
Database updates fail when using non-default database path

### ISSUE THREAD

**Issue by ridizy** [nosmokingbandit/Watcher3#123]
After an upgrade that requires a database update, Watcher3 will hang with the following message:
```
Connected to database sqlite:////NAS/apps/watcher/db/watcher.sqlite
Database update required. This may take some time.
Backing up database to /Applications/Watcher3/db.
Executing database update 2
```

If I move my database to the root of the Watcher3 directory, start it without passing it the `--db` argument, then the database gets updated and Watcher starts up as expected.  

I can then move my database back to my preferred location and continue starting Watcher using my preferred options:
```
python3 /Applications/Watcher3/watcher.py \
 --conf /NAS/apps/watcher/config/config.cfg \
 --log /NAS/apps/watcher/log \
 --db /NAS/apps/watcher/db/watcher.sqlite
```

I'm guessing that the database update code isn't taking into account the `--db` argument.

**Comment by nosmokingbandit** [comment]
I just tested a remote database file and it updated fine. Update 2 can take
some time since it has to iterate through every movie. How many movies do
you have and how long did you wait?

**Comment by ridizy** [comment]
About 1,800 movies and my DB is 1.8MB in size. This has happened to me several times with recent updates. I know I've waited at least 10 minutes in the past but when I see it happening now I usually just abort and do my db move trick. Then the update takes less than a minute. 

Maybe because my DB is over the network I should wait even longer?  It's a 1 gbps network connection to my filer with <1ms latency. I wouldn't think it would be that much slower but I guess I can't rule that out.

**Comment by nosmokingbandit** [comment]
It checks the database version when starting up, so until all of the update
methods are finished it will trigger every time Watcher starts.

I just pushed 4f10dbe721633c2c1a44ef205302474e8d0be94f, which shows a
progress % when updating so you can at least see how things are going. If
something breaks you should see an exception in the terminal window, so it
might just be taking a while.10 minutes does seem like a really long time
though.

**Comment by ridizy** [comment]
Thank you. I will let you know how the next update goes.

**Comment by ridizy** [comment]
The latest set of commits included a database upgrade and I had no issues updating this time.  Thank you!
