### ISSUE TITLE
Loose title matching

### ISSUE THREAD

**Issue by enilfodne** [nosmokingbandit/Watcher3#124]
I've recently noticed an issue with parsing movie titles, where a movie may include results from a completely different title. 

For example, the movie `Dunkirk` and the movie `Operation Dunkirk` are both released in `2017`, but `Operation Dunkirk` is misinterpreted as `Dunkirk` and included in the results; all the while being a completely different movie.

**Comment by nosmokingbandit** [comment]
I'm assuming you are using torrent searches? If you are using Usenet indexers this isn't a problem I can fix since they are searched using the movie's imdb #.

For torrents, release titles are matched against the actual movie title and have to match over a certain thre

**Comment by enilfodne** [comment]
Yes, exactly. But NZBhydra has an option to forgo imdb ids and generate queries based on the movie title (similar to torrents).

Perhaps tweaking the threshold or putting `uncertain` status?

**Comment by nosmokingbandit** [comment]
6d4a2b18aa54d4219b0df787d54b9632b0ea6c67

I ended up just writing my own title matching method. It fixed the problem with movies like Dunkirk but doesn't affect titles without that problem (at least that I could find in my tests).

**Comment by enilfodne** [comment]
Found another even worse case - `It`, however everything works as expected with the new fuzzy matching.

Thanks for the prompt reaction.

**Comment by nosmokingbandit** [comment]
I just checked It and I got no results until I enabled TS and similar release types, then I got all sorts of matches for TS. If it works for something as generic as 'It' I'm happy. Let me know if you notice anything else acting strangely.
