### ISSUE TITLE
Post-Processsing isn't working.

### ISSUE THREAD

**Issue by simpat1zq** [nosmokingbandit/Watcher3#127]
Here's the error I see in the logs. Please let me know if you need to see more of the log. :

INFO 2017-09-20 16:23:08,516 core.ajax.get_log_text: Dumping log file log.txt to text.
INFO 2017-09-20 16:22:45,925 CPTaskScheduler._task: == Finished Scheduled Task: PostProcessing Scan ==
UnboundLocalError: local variable 'movie_details' referenced before assignment
    self.fuzzy_title(titles, year=str(movie_details['year']))
  File "/home/osboxes/Watcher3/core/searchresults.py", line 81, in score
    search_result = self.score.score([search_result], imported=True)[0]
  File "/home/osboxes/Watcher3/core/library.py", line 880, in searchresults
    if core.manage.searchresults(data['guid'], 'Finished', movie_info=data):
  File "/home/osboxes/Watcher3/core/postprocessing.py", line 375, in complete
    response = self.complete(data)
  File "/home/osboxes/Watcher3/core/postprocessing.py", line 90, in POST
    pp.POST(**d)
  File "/home/osboxes/Watcher3/core/scheduler.py", line 107, in scan_directory
    self.task()
  File "/home/osboxes/Watcher3/core/cp_plugins/taskscheduler.py", line 209, in _task
Traceback (most recent call last):
WARNING 2017-09-20 16:22:45,924 CPTaskScheduler._task: Scheduled Task PostProcessing Scan Failed:
INFO 2017-09-20 16:22:45,924 core.searchresults.score_sources: Keeping 1 results.
DEBUG 2017-09-20 16:22:45,924 core.searchresults.score_sources: The.Loft.2014.mp4.2014.BluRay-720P is an import, skipping size check.
DEBUG 2017-09-20 16:22:45,924 core.searchresults.score_sources: The.Loft.2014.mp4.2014.BluRay-720P matches source BluRay-720P, checking size.
DEBUG 2017-09-20 16:22:45,924 core.searchresults.score_sources: Scoring and filtering The.Loft.2014.mp4.2014.BluRay-720P based on resolution BluRay-720P.
INFO 2017-09-20 16:22:45,924 core.searchresults.score_sources: Filtering resolution and size requirements.
INFO 2017-09-20 16:22:45,924 core.searchresults.freeleech: Adding Freeleech points.
INFO 2017-09-20 16:22:45,924 core.searchresults.seed_check: Keeping 1 results.
INFO 2017-09-20 16:22:45,923 core.searchresults.seed_check: Checking torrent seeds.
INFO 2017-09-20 16:22:45,923 core.searchresults.retention_check: Keeping 1 results.
INFO 2017-09-20 16:22:45,923 core.searchresults.retention_check: Checking retention.
DEBUG 2017-09-20 16:22:45,923 core.searchresults.reset: Resetting release scores to 0.

**Comment by nosmokingbandit** [comment]
I was in a hurry and neglected to comment, but commit d0dc523 should take care of this. Let me know if you still have problems.

**Comment by simpat1zq** [comment]
I forgot about this, so sorry for the late reply. But everything is working great. Thanks for all your work on this.
