### ISSUE TITLE
bad 'view changes' link

### ISSUE THREAD

**Issue by nephariouz** [nosmokingbandit/Watcher3#128]
When you click the "view changes" link on the update notification it goes to an incorrect page. The correct address gets appended to the end of the current address. For example the latest link goes to "http://192.168.1.30:9090/watcherhttps://github.com/nosmokingbandit/watcher3/compare/e50ef1ebe827bd6680050c2933357ac1f3a733a5...d0dc52397a48b95974a01e380d46b51e2031b3da" instead of the correct address.

**Comment by nosmokingbandit** [comment]
Should be back to normal, but you won't be able to see it until the next update. I'm closing this for now, but feel free to reopen if neccesary.
