### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#129]
INFO 2017-09-29 14:04:22,680 core.ajax.get_log_text: Dumping log file log.txt to text.
INFO 2017-09-29 14:04:13,450 cherrypy.error.140514626279520.error: [29/Sep/2017:14:04:13] HTTP 
TypeError: can only join an iterable
    meta_data['edition'] = ' '.join(meta_data['edition'].sort())
  File "/app/watcher/core/library.py", line 564, in parse_filename
    titledata = self.parse_filename(filepath)
  File "/app/watcher/core/library.py", line 435, in from_file
    mdata = self.metadata.from_file(data['movie_file'], imdbid=data.get('imdbid'))
  File "/app/watcher/core/postprocessing.py", line 230, in get_movie_info
    data.update(self.get_movie_info(data))
  File "/app/watcher/core/postprocessing.py", line 80, in POST
    return self.callable(*self.args, **self.kwargs)
  File "/app/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/app/watcher/lib/cherrypy/lib/jsontools.py", line 61, in json_handler
    self.body = self.oldhandler(*args, **kwargs)
  File "/app/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    response.body = self.handler()
  File "/app/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
Traceback (most recent call last):
ERROR 2017-09-29 14:04:13,447 cherrypy.error.140514626279520.error: [29/Sep/2017:14:04:13] HTTP 
INFO 2017-09-29 14:04:13,447 core.library.parse_filename: Found {'year': 2017, 'resolution': '1080p', 'quality': 'BluRay', 'codec': 'x264', 'group': 'DRONES', 'unrated': True, 'edition': ['UNRATED'], 'title': '', 'release_name': ''} in filename.
INFO 2017-09-29 14:04:13,447 core.library.parse_filename: Parsing directory name for movie information: Wish.Upon.2017.UNRATED.1080p.BluRay.x264-DRONES.
INFO 2017-09-29 14:04:13,446 core.library.from_file: Gathering metadata for /data/downloads/movies/*********.
INFO 2017-09-29 14:04:13,446 core.postprocessing.get_movie_info: Movie data found locally by imdbid.
DEBUG 2017-09-29 14:04:13,445 core.sqldb.execute: Executing SQL command: ['SELECT * FROM MOVIES WHERE imdbid="tt5322012"']
DEBUG 2017-09-29 14:04:13,445 core.sqldb.get_movie_details: Retrieving details for movie tt5322012.
INFO 2017-09-29 14:04:13,445 core.postprocessing.get_movie_info: Searching local database by imdbid.
INFO 2017-09-29 14:04:13,445 core.postprocessing.get_movie_info: Local release info found by guid.
DEBUG 2017-09-29 14:04:13,444 core.sqldb.execute: Executing SQL command: ['SELECT * FROM SEARCHRESULTS WHERE guid="********" ORDER BY score DESC, size DESC']
DEBUG 2017-09-29 14:04:13,444 core.sqldb.get_single_search_result: Retrieving search result details for *********.
INFO 2017-09-29 14:04:13,444 core.postprocessing.get_movie_info: Searching local database for guid.
INFO 2017-09-29 14:04:13,444 core.postprocessing.POST: Gathering release information.
INFO 2017-09-29 14:04:13,444 core.postprocessing.get_movie_file: Post-processing file /data/downloads/movies/************.
INFO 2017-09-29 14:04:13,444 core.postprocessing.get_movie_file: Finding movie file.
DEBUG 2017-09-29 14:04:13,444 core.postprocessing.POST: {'guid': '', 'path': '/data/downloads/movies/******', 'apikey': '*******', 'downloadid': '1417', 'mode': 'complete'}
INFO 2017-09-29 14:04:13,444 core.postprocessing.POST: #################################
INFO 2017-09-29 14:04:13,444 core.postprocessing.POST: Post-processing request received.
INFO 2017-09-29 14:04:13,444 core.postprocessing.POST: #################################

**Comment by jaketame** [comment]
This is now resolved after the above commit.

**Comment by nosmokingbandit** [comment]
Huzzah!

Thanks for reporting back.
