### ISSUE TITLE
Parsing wrong infos

### ISSUE THREAD

**Issue by j0hnsen** [nosmokingbandit/Watcher3#13]
Hey,
I see often not renamed releases as you only try to get the release name from filename.

INFO 2017-04-07 21:27:40,983 core.library.parse_filename: Parsing /PATH/TO/FOLDER/John.Wick.2014.German.AC3D.5.1.DL.720p.BluRay.x264-XDD/JEtzaFunzTOllASwIda_005/fun.mkv for movie information.
INFO 2017-04-07 21:27:40,983 core.library.parse_filename: Found {'container': 'mkv', 'title': 'fun'} in filename.

Now the filename is set to fun but the search string should be john wick instead... Could you fix that?

**Comment by nosmokingbandit** [comment]
I use the release info if it can be found from the download. If you use NZBHydra it gives Watcher one link, then resolves it to the actual nzb url when sending it to your download client. 

If the urls are different Watcher tries the download id # supplied by your downloader (if there is one, some torrent clients don't provide download ids). If that fails it parses the filename. If this doesn't look good it tries the parent folder, which wouldn't help in your case anyway.

I'll need a large chunk of your log if you want me to look into this more. watchernzb@gmail.com Most problems like this are from NZBHydra complicating download urls.

**Comment by j0hnsen** [comment]
I don't use hydra with watcher and send you a log. There are more and more false matchings :(

**Comment by nosmokingbandit** [comment]
I'm looking through your log and I just want to make sure -- are you using NZBGet? It should be able to find the movie based on download id, but it isn't and I want to run a few tests to see what is going on.

**Comment by j0hnsen** [comment]
Yep running nzbget 17.x have massiv problems with 18.x server is debian based latest stable.

**Comment by nosmokingbandit** [comment]
I can't find anything in the log you sent that indicates where the problem is coming from.

When an nzb gets sent to nzbget do you get a log line similar to this?

`INFO 2017-04-09 21:08:13,099 core.downloaders.nzbget.add_nzb: NZB sent to NZBGet - downloadid 123`

**Comment by j0hnsen** [comment]
Yep I got this messages. Tried nzbget 18 again same problem it seems that watcher still can't find any matching release @ imdb. So it's not renamed or renamed to a wrong title... :(

**Comment by nosmokingbandit** [comment]
36de211e5010b42a318ea7a1b6ed19e8a1a0e884 *should* fix this.

As usual, it is something stupid. NZBGet sends me the download id as an integer, but I store them as strings since other applications use strings. But a sql query for an int in a text column will never get results.

In other words, numbers aren't letters and I forgot that for a minute.

Let me know what happens.

**Comment by j0hnsen** [comment]
Still wrong matches and so the release is not renamed correct.

**Comment by j0hnsen** [comment]
Seems to work now but got some errors with PP script in nzbget.
Changed response = json.loads(urllib.request.urlopen(request, timeout=600).read())
to response = json.loads(urllib.request.urlopen(request, timeout=600).read().decode('utf-8')) and it works fine.

**Comment by nosmokingbandit** [comment]
I'm still getting used to unicode in python 3. I'll make that change official, just make sure you set yours back to normal or git will throw an error when trying to update.
