### ISSUE TITLE
Missing poster images showing as broken image not placeholder

### ISSUE THREAD

**Issue by smidgedy** [nosmokingbandit/Watcher3#132]
Hi Guys,

This is my first ever issue report so please be gentle...

### Description
I have a number of movies in my database where Watcher *thinks* I have a poster downloaded, but the poster file doesn't exist (how this has happened might be a separate issue). Looking at the code it appears that normally when the database is missing a filename for the poster, `static/js/library/status.js` will use `images/missing_poster.jpg` in its place:

```javascript
movie["poster"] = (movie["poster"] || "images/missing_poster.jpg")
```

Because these files are mentioned in the database, the JS validation thinks that the file is all good, and instead of getting a beautiful "poster unavailable" image I get a broken image placeholder that in some cases is 900px tall and breaks the UX a bit. 

### How to replicate
The issue can be replicated by going into the static/images/posters folder under your Watcher3 install folder and deleting a bunch of images.

### Suggestions
Back-of-the-cocktail-napkin thoughts on this include:

* Amend `core/sqldb.py` to check for the existence of poster image files before returning a result, blank the poster file name if it doesn't exist, perhaps update the library to reflect that the file is gone.
* IDK? Perhaps have a task to periodically scan for that issue? I like the first option, go with that.

### inb4 "fix it yourself"
I don't write a lot of python in my day-to-day but I'd actually love to implement this. If the right people are happy with this approach, and if pull requests are being accepted, I wouldn't mind patching this myself. I'm still currently just trawling through the code to get my head around how things work around here, but it's a cool project and I'd be happy to help on tiny little things like this.

**Comment by nosmokingbandit** [comment]
Your proposed fix would be somewhat inefficient. There are 50 images in each page of movies and running 50 checks against the hdd for each pageload would take a rather long time (milliseconds realistically, but that could still double the time to render the page).

Every 72 hours the Metadata Update task runs and will re-download missing posters if they aren't in your posters directory. This doesn't fix the source of the problem, but it should resolve itself eventually. You can also manually redownload posters in <watcher_url>/library/manage/, select all of the movies with missing posters, then click the blue tag button.

What browser and OS are you using? On (Chrome([http://oi68.tinypic.com/2u75dds.jpg] and Firefox missing posters don't break the page layout.

Are the missing posters from recently-added movies, or does it seem random? If you want I'll take a look through your logs if you want to send a copy to `watchernzb@gmail.com`

**Comment by smidgedy** [comment]
Hi!

Cheers for the response - in principle I agree that it's an inefficient solution, as the overhead scales in a linear fashion with additional images. In some very non-scientific testing I ran, I can see that the initial page renders on my system in around 71ms, with a total load time of 760ms (first load from a clear cache) or about 330ms cached. On the same system 50 calls to os.path.isfile() with different, randomly generated filenames each time takes 4.4ms. I tested up a few orders of magnitude and 500 calls takes about 44ms, and 5000 would take about 440ms roughly.

Appreciate if you're keeping it lean though, and can absolutely live without it. I'll have a look and see if I can provide more information about what is causing the mismatch between the files saved to disk and the database, as it's probably a better place to address the issue. Perhaps, in fact, a check that the file exists before saving that piece of metadata might be a good alternative, would easily be faster/leaner.

That being said - I haven't actually experienced 72 hours of uptime with Watcher yet as I've been testing, learning, and playing with it on my main machine before moving it off to the torrent box where it now runs happily. I ran the metadata update task manually from the system settings, and it didn't fix the missing images. manually triggering a metadata refresh from the detail view worked. I'll leave it a few days and see.

Here's a few notes about the missing images:

* Can confirm that it's new movies imported from the trakt.tv lists.
* Appears to be somewhat deterministic - I can create a new installation in a fresh folder, run watcher, enable the 'collected' list, manually start the task, and the same images will be missing each time (tested 5 times).
* Logs don't appear to reveal anything different between successful or missing imports, I'll email through a full log from one of these test installs (only ~200 lines).
* Have tested across two machines, both running Windows 10 / Chrome
* Also tested on a Ubuntu VM / Firefox, however all images failed on this system
* Layout breaks in Chrome in the single movie detail view (i.e. click on a poster in the status view)

Hope this helps!

**Comment by nosmokingbandit** [comment]
After 9cd9ac913f2294f6cc0a2f58cc2e5ce56a5d5fae everything should be working as expected.

I'll fix the css for broken image links soon, though with any luck it won't be necessary.

Let me know if this doesn't fix things on your end.

**Comment by smidgedy** [comment]
Great, amazing, fantastic!

This and the later patch to fix css are perfect. Thanks for this awesome project!
