### ISSUE TITLE
Request - Trim Logging Output

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#134]
Upon looking at the logs when the searching for movies, can we stop the logging if they are disabled?

DEBUG 2017-10-07 17:58:56,709 core.snatcher.grab_all: 21 & Over is Disabled, skipping.
DEBUG 2017-10-07 17:58:56,709 core.snatcher.grab_all: 21 is Disabled, skipping.
DEBUG 2017-10-07 17:58:56,709 core.snatcher.grab_all: 2001: A Space Odyssey is Disabled, skipping.
DEBUG 2017-10-07 17:58:56,709 core.snatcher.grab_all: 2 Guns is Disabled, skipping.
DEBUG 2017-10-07 17:58:56,709 core.snatcher.grab_all: 2 Fast 2 Furious is Disabled, skipping.
DEBUG 2017-10-07 17:58:56,709 core.snatcher.grab_all: 17 Again is Disabled, skipping.
DEBUG 2017-10-07 17:58:56,709 core.snatcher.grab_all: 16 Blocks is Disabled, skipping.
DEBUG 2017-10-07 17:58:56,709 core.snatcher.grab_all: 13 Hours: The Secret Soldiers of Benghazi is Disabled, skipping.
DEBUG 2017-10-07 17:58:56,709 core.snatcher.grab_all: 127 Hours is Disabled, skipping.
DEBUG 2017-10-07 17:58:56,709 core.snatcher.grab_all: 12 Years a Slave is Disabled, skipping.
DEBUG 2017-10-07 17:58:56,708 core.snatcher.grab_all: 100 Streets is Disabled, skipping.
DEBUG 2017-10-07 17:58:56,708 core.snatcher.grab_all: 10,000 BC is Disabled, skipping.
DEBUG 2017-10-07 17:58:56,708 core.snatcher.grab_all: 10 Things I Hate About You is Disabled, skipping.
DEBUG 2017-10-07 17:58:56,708 core.snatcher.grab_all: 10 Cloverfield Lane is Disabled, skipping.

**Comment by nosmokingbandit** [comment]
I like to keep the debug level fairly verbose so it is easier to see exactly what is going on. If you want to read your logs easier I made a custom language for notepad++ that helps separate different log levels.

https://gist.github.com/nosmokingbandit/729719bff47ca3c5198c8d424d07d445
