### ISSUE TITLE
qBitTorrent downloader breaks with authentication turned on

### ISSUE THREAD

**Issue by smidgedy** [nosmokingbandit/Watcher3#135]
Hi!

I use the qBitTorrent downloader with authentication turned on, and it appears to break after time. Snatching works when Watcher starts, but it appears that the authenticated session with qBitTorrent expires over time and isn't renewed by watcher when snatching.

Here's the (sanitized) log from a failed attempt:
```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    raise JSONDecodeError("Expecting value", s, err.value) from None
  File "<INSTALL PATH>\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "<INSTALL PATH>\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    return _default_decoder.decode(s)
  File "<INSTALL PATH>\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    response = json.loads(Url.open(url, headers=headers).text)
  File "<INSTALL PATH>\Watcher3-master\core\downloaders\qbittorrent.py", line 92, in _get_download_dir
Traceback (most recent call last):
ERROR 2017-10-08 11:57:15,039 core.downloaders.qbittorrent._get_download_dir: QBittorrent unable to get download dir.
WARNING 2017-10-08 11:57:15,039 root.open: Error code 403 in response from http://<IP ADDRESS>:8080/query/preferences
DEBUG 2017-10-08 11:57:15,024 core.downloaders.qbittorrent._get_download_dir: Getting default download dir for QBittorrent.
INFO 2017-10-08 11:57:15,024 core.downloaders.qbittorrent.add_torrent: Sending torrent <NAME OF THE FILE> to QBittorrent.
INFO 2017-10-08 11:57:15,024 core.snatcher.snatch_torrent: Sending magnet to QBittorrent.
INFO 2017-10-08 11:57:15,024 core.snatcher.download: Sending <NAME OF THE FILE> to download client.
```

You can see the 403 response from qBitTorrent - at this point it seems like Watcher has an expired cookie. Now I couldn't see anything in the qBitTorrent docs about cookies expiring, so it may be a bug at their end but would it be worth testing API calls for a 403 response, logging back in, and trying again?

For now I'm working around it by either turning off authentication.

Thanks again!

**Comment by nosmokingbandit** [comment]
Seems like the cookie QBit uses for authentication expires after a while. I'm refactoring a lot of my Qbittorrent module to account for this so I'll have a fix relatively soon.

**Comment by smidgedy** [comment]
[Thanks!](https://i.pinimg.com/736x/c2/32/67/c23267975db501aeb138deda6f1f44f6--youre-awesome-awesome-dogs.jpg) I'm happy to close this off then if you prefer?

**Comment by nosmokingbandit** [comment]
I'll leave this open until the fix is committed. I have a little more testing, but I've been able to close/open QBit several times, with several auth cookie changes with no problems at all, I just want to test a few more specific instances before I commit.

**Comment by nosmokingbandit** [comment]
1c914a4 Should fix the auth expiring with QBit. Let me know if you still have problems.

**Comment by smidgedy** [comment]
Have left it running for quite a while now with no drama. Running silky smooth thank you!
