### ISSUE TITLE
Unable to start after git pull

### ISSUE THREAD

**Issue by barbequesauce** [nosmokingbandit/Watcher3#138]
I attempted an update this afternoon (popup said ~250 updates pending). It seemed to hang, so after a half hour I killed the process and attempted a git pull. It seems I'm up to date now.

However, when I attempt to launch, I receive the following FileNotFound error. It seems as if the --db flag is not being processed?

```
 pi@home:/opt/Watcher3 $ sudo -u watcher3 -g watcher3 python3 /opt/Watcher3/watcher.py --daemon --conf /opt/Watcher3/config.cfg --log /opt/Watcher3/logs/log.txt --db /opt/Watcher3/watcher.sqlite 
Traceback (most recent call last):
  File "/opt/Watcher3/watcher.py", line 52, in <module>
    shutil.copy(f, dst)
  File "/usr/lib/python3.4/shutil.py", line 228, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.4/shutil.py", line 108, in copyfile
    with open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'userdata/watcher.sqlite'
pi@home:/opt/Watcher3 $ ls
backup.py   lib          logs          __pycache__  static     watcher.py
config.cfg  license.txt  plugins       README.md    templates  watcher.sqlite
core        locale       post scripts  run scripts  tox.ini
pi@home:/opt/Watcher3 $ 

```

**Comment by nosmokingbandit** [comment]
Looks like it might not have cloned everything correctly. Try running:
```
git reset --hard
git pull
```

**Comment by barbequesauce** [comment]
Yep, that led me to the discovery that the develop branch no longer exists. Reset to master, hard reset & pull, and a couple permissions fixes and I’m back in business

Thanks!

**Comment by nosmokingbandit** [comment]
Did you intentionally clone develop? I make branches to work on major changes so I can run an update without pushing changes to master. You never want to run anything but master unless you are some sort of weird masochist.

**Comment by barbequesauce** [comment]
Heh. 

On most of the other projects in this space (cp, sg, Mylar, ll, hp as examples) the develop / development branch is akin to a beta group while master is more of a golden release group. I’d assumed you would operate the same way and switched to develop ages ago... my mistake...

**Comment by nosmokingbandit** [comment]
Since there is only one dev (me!) I don't really need to share my work with anyone. I mostly just work in a copy on my pc rather than having a separate branch for it.
