### ISSUE TITLE
Lets multiple words preferred stack the score

### ISSUE THREAD

**Issue by PotatoQuality** [nosmokingbandit/Watcher3#14]
Hi,

i have a big preferred word list to manage not taking bad release groups. It will be nice if watcher look at multiple words and stack the score by every hit.
Now it will stop finding by 1 and raise the score only by 10.
But to have a bigger score impact, it will be nice if watcher stack the score by finding multiple matches :)

**Comment by nosmokingbandit** [comment]
Fixed in ce25d475f83ed36d6772f0cc35ef020d5e47c94b.
I'm not sure why I wrote it that way - it was supposed to compound preferred words all along.
