### ISSUE TITLE
Post Processing failing

### ISSUE THREAD

**Issue by ragman666** [nosmokingbandit/Watcher3#141]
Since the latest updates post processing is failing

INFO 2017-11-01 21:26:40,882 CPTaskScheduler._task: == Finished Scheduled Task: PostProcessing Scan ==
DEBUG 2017-11-01 21:26:40,811 core.sqldb.execute: Executing SQL command: ['UPDATE TASKS SET last_execution=? WHERE name=?', ('2017-11-01 21:26:40', 'PostProcessing Scan')]
DEBUG 2017-11-01 21:26:40,811 core.sqldb.update: Updating last_execution to 2017-11-01 21:26:40 for rows that match name:PostProcessing Scan in TASKS.
DEBUG 2017-11-01 21:26:40,810 core.sqldb.execute: Executing SQL command: ['SELECT 1 FROM TASKS WHERE name="PostProcessing Scan"']
DEBUG 2017-11-01 21:26:40,810 core.sqldb.row_exists: Checking if name="PostProcessing Scan" exists in database table TASKS
AttributeError: 'Postprocessing' object has no attribute 'POST'
    pp.POST(**d)
  File "C:\Program Files\Watcher\Watcher3\core\scheduler.py", line 118, in scan_directory
    self.task()
  File "C:\Program Files\Watcher\Watcher3\core\cp_plugins\taskscheduler.py", line 252, in _task
Traceback (most recent call last):
WARNING 2017-11-01 21:26:40,810 CPTaskScheduler._task: Scheduled Task PostProcessing Scan Failed:
INFO 2017-11-01 21:26:40,810 core.scheduler.scan_directory: Found match for The Dark Tower 2017 720p BluRay DTS TiTAN[EtHD] in releases: The Dark Tower 2017 720p BluRay DTS TiTAN[EtHD].
DEBUG 2017-11-01 21:26:40,808 core.sqldb.execute: Executing SQL command: ['SELECT * FROM SEARCHRESULTS WHERE title="The Dark Tower 2017 720p BluRay DTS TiTAN[EtHD]" ORDER BY score DESC, size DESC']
DEBUG 2017-11-01 21:26:40,808 core.sqldb.get_single_search_result: Retrieving search result details for The Dark Tower 2017 720p BluRay DTS TiTAN[EtHD].
INFO 2017-11-01 21:26:40,808 core.scheduler.scan_directory: Processing D:\Torrents\Watcher\The Dark Tower 2017 720p BluRay DTS TiTAN[EtHD].
INFO 2017-11-01 21:26:40,808 core.scheduler.scan_directory: Scanning D:\Torrents\Watcher for movies to process.
INFO 2017-11-01 21:26:40,807 CPTaskScheduler._task: == Executing Scheduled Task: PostProcessing Scan ==

**Comment by jaketame** [comment]
I can confirm I'm also receiving this error

**Comment by thijskaspers** [comment]
Me too, same error:

Checking if name="PostProcessing Scan" exists in database table TASKS
AttributeError: 'Postprocessing' object has no attribute 'POST'
pp.POST(**d)
File "Watcher3/core/scheduler.py", line 118, in scan_directory
self.task()

**Comment by thijskaspers** [comment]
Found out it's not saving the settings either. If I change the scan frequency to 10m instead of the default 15m at the directory scanner, it says saved successfully, but after a reload it's still at 15m.

**Comment by deadc0de6** [comment]
I can confirm both issues above on 3c71c0129
```
AttributeError: 'Postprocessing' object has no attribute 'POST'
    pp.POST(**d)
  File "/watcher/core/scheduler.py", line 118, in scan_directory
    self.task()
  File "/watcher/core/cp_plugins/taskscheduler.py", line 252, in _task
Traceback (most recent call last):
WARNING 2017-11-05 16:52:05,572 CPTaskScheduler._task: Scheduled Task PostProcessing Scan Failed:
```

also changing the frequency is not saved

**Comment by nosmokingbandit** [comment]
874cb715089583d6c17c14ae027d19e5b065a95c fixes the scan problem, just a stupid oversight from when I cleaned up a few things a while ago.

As far as the timer not setting....
I originally had a minimum value of 15 minutes because there was nothing in place to keep the scheduler from starting a scan while one was already happening, which can cause all sorts of weird problems. I forgot to go back and fix that in the scheduler since it was really early on in the development of the scheduler. Anyway, the scheduler now cannot run the same task twice simultaneously, and as of ba5a56414d867037685f1eff8f9090e9aa5041be you can set it as low as 5 minutes.

**Comment by ragman666** [comment]
Tested and working following updates

**Comment by thijskaspers** [comment]
Thanks guys!
