### ISSUE TITLE
500 Internal Server Error - couchpotato import

### ISSUE THREAD

**Issue by MechEng70** [nosmokingbandit/Watcher3#143]
Hello,

trying to import my database from couchpotato.  Enter in 0.0.0.0 and 5050 with the api key.  all this works for the android apps that i use.

When the "scan library" is clicked the 500 internal server error shows up.

`INFO 2017-11-04 23:27:24,851 core.ajax.get_log_text: Dumping log file log.txt to text.
  ACCEPT-ENCODING: gzip, deflate
  Content-Length: 63
  Remote-Addr: 172.16.5.171
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  USER-AGENT: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.75 Safari/537.36
  ORIGIN: http://172.16.5.250:9090
  HOST: 172.16.5.250:9090
  ACCEPT: */*
  DNT: 1
  ACCEPT-LANGUAGE: en-US,en;q=0.9
  CONNECTION: keep-alive
  COOKIE: user="2|1:0|10:1507330312|4:user|44:NmJiZjcxOTg0MzMxNGRlYjhmZjcwODQ4NjliOGQ2Mjk=|20bd29f2b7cfc9f8f0031cd0b13a078e33bfcbc267cbce9399d97608b429b530"; redirect=0; sickrage_user="2|1:0|10:1509284054|13:sickrage_user|44:NTQ3OWY0ZDU3ZDI5NmU0Njk4NzI4NWM5YTZlMWQ3ODQ=|953f77046c3130feeddaba48bd8493d8379c00bf5ad554c2bd0a8509493aee7d"; manage_view=thumb; login_cookie=c747e5aa293545c68a528d3260faa130e205ee2f; login_salt=545; snatched_view=list; soon_view=thumb; suggest_view=thumb; late_view=list; advanced_toggle_checked=1; blu_ray_com_new_releases_view=thumb; imdb_movies_in_theaters_view=thumb; imdb_box_office_view=thumb; imdb_top_250_movies_view=thumb; wanted_view=thumb; session=93b0fd8a46758fcaa03d539de7eeb41ea79249a6
  X-REQUESTED-WITH: XMLHttpRequest
  REFERER: http://172.16.5.250:9090/library/import/couchpotato
Request Headers:
INFO 2017-11-04 23:27:19,201 cherrypy.error.140055252175336.error: [04/Nov/2017:23:27:19] HTTP 
KeyError: 'info'
    name = i['info']['name']
  File "/home/plex/.watcher3/core/library.py", line 355, in get_movies
    return library.ImportCPLibrary.get_movies(url)
  File "/home/plex/.watcher3/core/ajax.py", line 1048, in get_cp_movies
    return self.callable(*self.args, **self.kwargs)
  File "/home/plex/.watcher3/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "/home/plex/.watcher3/lib/cherrypy/lib/jsontools.py", line 61, in json_handler
    self.body = self.oldhandler(*args, **kwargs)
  File "/home/plex/.watcher3/lib/cherrypy/lib/encoding.py", line 220, in __call__
    response.body = self.handler()
  File "/home/plex/.watcher3/lib/cherrypy/_cprequest.py", line 670, in respond
Traceback (most recent call last):
ERROR 2017-11-04 23:27:19,186 cherrypy.error.140055252175336.error: [04/Nov/2017:23:27:19] HTTP 
DEBUG 2017-11-04 23:27:19,185 core.library.get_movies: Parsing CouchPotato movie 400 Days
DEBUG 2017-11-04 23:27:19,185 core.sqldb.execute: Executing SQL command: ['SELECT * FROM MOVIES  ORDER BY title ASC, sort_title ASC']
DEBUG 2017-11-04 23:27:19,185 core.sqldb.get_user_movies: Retrieving list of user's movies.
INFO 2017-11-04 23:27:19,011 core.library.get_movies: Reading CouchPotato library.`

**Comment by nosmokingbandit** [comment]
4ed709bf920a111dd74abe92ac47ce8635c5442b should take care of this. CP's output may not be super consistent but this fix uses the more basic epoch timestamp to parse dates which is consistent by design.

**Comment by MechEng70** [comment]
4ed709b did not work... 
Then updated to 874cb71 and still getting the 500 Internal Server Error

**Comment by nosmokingbandit** [comment]
It is likely a different error than the first time around -- trying to convert another application's data structure to match mine is complicated. Can you grab a part of the log for me?

**Comment by MechEng70** [comment]
[log.txt](https://github.com/nosmokingbandit/Watcher3/files/1452175/log.txt)

**Comment by nosmokingbandit** [comment]
Heh, sorry about that one. Should be all good after 623ba5a81240845bc01111008939fe63ea344f6a

**Comment by MechEng70** [comment]
still have issues with import on c4f8d2a4

[log (2).txt](https://github.com/nosmokingbandit/Watcher3/files/1459522/log.2.txt)

**Comment by nosmokingbandit** [comment]
c4f8d2a4b18b3f6f9f460f75b10a805d5e618d44 *should* take care of all of this.
I only ever had a few movies in CP since it never worked correctly so I
assumed the library export would match the output I got. Apparently that
isn't the case and this commit will probably prevent parsing errors but it
is hard to tell until something breaks again.

Thanks for your patience, keep me updated.

**Comment by MechEng70** [comment]
thanks... still getting the 500 internal error...

here is the latest logs.txt
[log.txt](https://github.com/nosmokingbandit/Watcher3/files/1464170/log.txt)

**Comment by nosmokingbandit** [comment]
If you are annoyed by this be assured that I'm twice as annoyed at my own stupidity. 

db8bcb6cf794190e178c5bd829b427c2aea6ebbc should get everything going again. I just ran an import of a few movies and i couldn't get it to break.

**Comment by MechEng70** [comment]
Sorry to continue the saga.... 
Currently on 1ad5ee

[log (2).txt](https://github.com/nosmokingbandit/Watcher3/files/1473038/log.2.txt)

**Comment by nosmokingbandit** [comment]
Rather than going back and forth lets make this easier for both of us.

Can you go to `http://localhost:5050/api/your-couchpotato-api-key/movie.list/` (change the address if necessary, of course) and send me the contents at `watchernzb@gmail.com`?

The log is saying that the couchpotato output for a certain movie doesn't have the 'info' key, which doesn't make any sense to me since that is where all of the info is.

**Comment by nosmokingbandit** [comment]
Thanks again for the email, commit 1ad5ee59c9c688192a9e13bf471dd7bbfabee3d3 was working for me with your movies list. Let me know either way what happens.

**Comment by MechEng70** [comment]
see email.  latest commit still having error.  sent log and movies list...  thanks.

**Comment by nosmokingbandit** [comment]
4a1794296dcc9154c9d59374fdb75ec0b0c5f321

Thanks for re-sending the output, it helped a lot.

Your entire library imported for me, so I'm hoping this takes care of all of CP's inconsistencies.

**Comment by MechEng70** [comment]
Success!!!  Great job!

**Comment by nosmokingbandit** [comment]
Ugh, lets not go through that again. Thanks for the help.

**Comment by MechEng70** [comment]
How does one support you guys?  Coffee or beer button?

**Comment by nosmokingbandit** [comment]
Well, I'm the only dev, and you can send a few dollars to a charity you like.
