### ISSUE TITLE
Restoring backup doesn't work

### ISSUE THREAD

**Issue by alexanderadam** [nosmokingbandit/Watcher3#145]
I don't know whether it should work already but it doesn't seem to work properly.

After selecting the backup zip and clicking the green `Restore Backup` button, the orange notification "Select a ZIP file" appears".

![image](https://user-images.githubusercontent.com/372620/32485107-7c3279ec-c3a2-11e7-97bf-145e24267ed1.png)

Afterwards the green button is still active but won't do anything anymore.

**Comment by nosmokingbandit** [comment]
Assuming the zip isn't corrupt, 829cbaeebd04fe211b2a14ca4133010732f1da42 will get everything working again. I removed the client-side file check, which is fine since the server still makes sure everything is correct.

**Comment by alexanderadam** [comment]
Wow, you are fast!
The file isn't corrupt. I can unpack the zip manually.

I will test it when I can login again. I just ran into another bug. 😉 

PS: you probably meant commit https://github.com/nosmokingbandit/Watcher3/commit/623ba5a81240845bc01111008939fe63ea344f6a

**Comment by alexanderadam** [comment]
Bugfix works like charm! Thank you! 👍
