### ISSUE TITLE
Disabling authentication caused some problems

### ISSUE THREAD

**Issue by alexanderadam** [nosmokingbandit/Watcher3#146]
I had authentication enabled and wanted to remove it again. But somehow the authentication still appeared although the checkbox was unchecked. So I removed (= blanked) username and password.

Well, and now the authentication still appears and won't accept my old credentials. And it won't accept blank credentials neither. 😉 

**EDIT:** Ah it required a restart!

**Comment by nosmokingbandit** [comment]
Did you restart Watcher after turning auth off?

**Comment by alexanderadam** [comment]
No (I wrote that in the edit part).
I guess it would make sense to restart watcher automatically in that case. Otherwise these inconsistencies may happen.

**Comment by nosmokingbandit** [comment]
The config page tells you what options require a restart to take effect. Restarting automatically is a bad idea, the user should have complete control over that.

I'm going to close this since things are working.
