### ISSUE TITLE
Multilanguage support for movies

### ISSUE THREAD

**Issue by alexanderadam** [nosmokingbandit/Watcher3#147]
I guess it's complicated but it would be nice to chose some language preferences.

**Comment by nosmokingbandit** [comment]
How do you mean? I'm lucky enough to speak English first so I don't have to personally worry about other languages. You can set up a quality profile that requires whatever language you want to be in the title of the release.

**Comment by alexanderadam** [comment]
Ah sure. Quality profile should be enough. I didn't think of that.
Thank you 👍
