### ISSUE TITLE
added recommendations

### ISSUE THREAD

**Issue by phynias** [nosmokingbandit/Watcher3#153]
added movie recommendations to watcher.
please let me know what you think and if you have any suggestions.
https://github.com/nosmokingbandit/Watcher3/pull/152

![cap1](https://user-images.githubusercontent.com/10147213/32991603-3e489904-ccf3-11e7-9253-a41de2f41e03.PNG)

![cap2](https://user-images.githubusercontent.com/10147213/32991605-40ce83e6-ccf3-11e7-96fb-2d3d6764c921.PNG)

**Comment by phynias** [comment]
i will add the only annoying thing is when nothing is found for a "Similar" recommendation, it just shows a blank page. i couldn't find a nice way to put a message like "Nothing found"

**Comment by nosmokingbandit** [comment]
Closing this, thanks for the work!
