### ISSUE TITLE
Borders on browser

### ISSUE THREAD

**Issue by MaDTaZ** [nosmokingbandit/Watcher3#162]
Since the update my browser look like this.  I have check it in chrome, firefox and safari.

![chrome_2017-11-29_11-37-40](https://user-images.githubusercontent.com/12501760/33395277-dbbe53b4-d4f9-11e7-8d8e-e06f39f7f097.png)

**Comment by MaDTaZ** [comment]
Fixed it for some reason commit were all screwed up.  Had to revert to a master

**Comment by nosmokingbandit** [comment]
That's.... weird. Something must have cloned weird when updating. I was playing around with UI kit for the frontend in a fork, but that shouldn't have affected the master branch.

At least everything is working good again.

**Comment by MaDTaZ** [comment]
Ya I figures after I saw that you were playing around.  It is all good figured out pretty quick
