### ISSUE TITLE
Imported movie file location: NULL

### ISSUE THREAD

**Issue by jerryawade** [nosmokingbandit/Watcher3#163]
After a period of time, the file shows null. At first, when I import movies in a folder, I input the path, instead of selecting it, the path with filename will show up in each individual movie that has been imported. After restarting or an unspecified time, the path no longer shows, shows as null, and now the file can no longer be deleted form the GUI.

**Comment by nosmokingbandit** [comment]
The logs record every time the database is modified. Look for any lines that contain `core.sql.update` or just `core.sql`. Or just send me all of your logs and I'll look through them to see what the deal is.

`watchernzb@gmail.com`
