### ISSUE TITLE
Update check failing

### ISSUE THREAD

**Issue by cdonovan** [nosmokingbandit/Watcher3#164]
Ever since the large refactor, I get the following error when the app checks for updates:

"Error Checking for Updates 
Current local hash not in git history."

The error in the logs is not much more informative:
`ERROR 2017-12-01 08:48:37,669 core.version._update_check: Current local hash not in git history.`

Any help in getting the updater back in order would be great.

**Comment by enilfodne** [comment]
The commit was (for all intents and purposes) deleted, so you'll have to reset your local repo to the latest origin:

```sh
git fetch origin
git reset --hard origin/master
git clean -f -d
```

**Comment by cdonovan** [comment]
That fixed it.  Thanks for the ultra-fast response!
