### ISSUE TITLE
Network Share Acess

### ISSUE THREAD

**Issue by KungFuCow** [nosmokingbandit/Watcher3#165]
Is there a way to get Watcher to import a video library stored on my NAS? I have tried using the UNC path and Watcher doesnt find any movies. I created a symlink to my network share which shows up as a regular folder in the root of C: but when I try to add it to Watcher, I get a Winerror 1326 which is invalid username\password. I can access the network share via symlink through Windows Explorer and it opens without prompting me for anything.

Any assistance would be greatly appreciated. Trying to migrate from CP.

**Comment by KungFuCow** [comment]
Figured it out. How to use NET USE to authenticate the NAS from the Windows machine.

**Comment by nosmokingbandit** [comment]
What protocol does your NAS use to share files? I server my media over samba and I'm able to scan the directory with `\\MediaSever\Movies`
