### ISSUE TITLE
Stopped working for me, style messed up?

### ISSUE THREAD

**Issue by thijskaspers** [nosmokingbandit/Watcher3#167]
Been using it without any issues, but all of a sudden this is what I'm seeing and logging in does not work:

![Imgur](https://i.imgur.com/bq0E0it.png)

I tried to reinstall / reclone Watcher and run it again, but the issue remains.

There are two issues that I can see in the browser inspector:

![Imgur](https://i.imgur.com/r8taF4b.png)

jQuery isn't loaded and it can't find the axion.min.js (it's looking in /auth/static/js/lib/axios.min.js?v=101)

What am I doing wrong?

Thanks in advance!

**Comment by nosmokingbandit** [comment]
A commit got all bungled up (I'd like to blame git, but it is probably entirely my fault even though I'm not 100% sure what happened).

You can either backup, re-clone, and restore or run the following commands in your watcher dir:

```
  git fetch origin  
  git reset --hard origin/master
  git clean -f -d
```

**Comment by thijskaspers** [comment]
Thanks for the reply! Unfortunately I already tried recloning the repo.

Tried your git commando's too for the hard reset, and I'm all up to date, but still it does not work.

**Comment by nosmokingbandit** [comment]
Your browser might be caching the old files. Refresh with shift+ctrl+r to
reset the cache.

**Comment by thijskaspers** [comment]
Tried refreshing it with shift+ctrl+r, and also tried Chrome incognito mode, no luck. Something is messed up.

I'm getting a 404 result on the "/auth/static/js/lib/axios.min.js?v=101" file, when I try to open the link directly from the chrome inspector. The login.js file is giving me an "Uncaught ReferenceError: $ is not defined" exception.

I'm running it on a Raspberry Pi with Python 3 by the way. Am I missing some dependencies or a wrong path? Weird, but thanks for looking into this!

**Comment by thijskaspers** [comment]
Allright, digged into it some more, found out the following:

There is no "axios.min.js" file in the lib folder on my Raspberry Pi.

I'm also seeing a difference in the source of the login.html file (in my browser) and what I'm seeing in the templates folder. Here's my source and as you can see there's no jquery indeed:

````<!DOCTYPE HTML5>
<html>
<html class="uk-background-secondary">
    <title>Watcher</title>
    <meta content="noindex, nofollow" name="robots">
    <meta content="" name="url_base">
    <meta content="width=device-width,initial-scale=1" name="viewport">
    <meta name="enable_notifs" content="false">

    <link rel="icon" type="image/png" href="/static/images/favicon.png">
    <link href="/auth/static/css/lib/materialdesignicons.min.css?v=101" rel="stylesheet">
    <link href="/auth/static/css/style.css?v=101" rel="stylesheet">
    <link href="/auth/static/css/themes/Default.css?v=101" rel="stylesheet">

    <link href="/auth/static/css/login.css?v=101" rel="stylesheet">
    <script src="/auth/static/js/lib/axios.min.js?v=101" type="text/javascript"></script>
    <script src="/auth/static/js/login.js?v=101" type="text/javascript"></script>


</head>
<body class="uk-background-default uk-box-shadow-medium">
    <div id="form">
        <div class="uk-inline">
            <i class="uk-form-icon mdi mdi-account"></i>
            <input id="user" class="uk-input" type="text">
        </div>

        <div class="uk-inline">
            <i class="uk-form-icon mdi mdi-lock"></i>
            <input id="password" class="uk-input" type="password">
        </div>
        <div>
            <a id="login">
                <i class="mdi mdi-login"></i>
            </a>
        </div>


    </div>
</body>
</html>
````

**Comment by thijskaspers** [comment]
I fixed it!

Not sure how, but I removed the entire watcher folder and found out that the login page was still accessible, so somehow the watcher port was still being used and it was accessing cache somewhere.. There was a python3 process still running. Killed that one and completely reinstalled everything and now it works!

Sorry for wasting your time on this, my bad.
