### ISSUE TITLE
Copy versus Move in webUI

### ISSUE THREAD

**Issue by barbequesauce** [nosmokingbandit/Watcher3#168]
I'm trying to chase down a weird file deletion issue, and I noticed this...

in the webUI under Post Processing, you have the option to select move / copy / hardlink / softlink the files. I select "copy" as they're seeding from that location, and hit save.

Then I navigate away to a different page. I come back, and "move" is selected again...

I'm on the current commit (as of posting this) - edbd12f37606b7e2e11e8d0bd92606db35e57be8.

**Comment by nosmokingbandit** [comment]
I'm not able to replicate this on either my testing server or my main server. Are other settings resetting or is it just that select box?

What does your config say in Postprocessing > movermethod ?

**Comment by barbequesauce** [comment]
Interesting... 

```
pi@pi:/opt/Watcher3/userdata $ cat config.cfg | grep -i mover
        "moverenabled": true,
        "movermethod": "copy",
        "moverpath": "/mnt/lts/movies/",
pi@pi:/opt/Watcher3/userdata $ 
```

I rebooted earlier and the action described originally is still current, despite the config data.

**Comment by nosmokingbandit** [comment]
What browser are you using? It might be a html or javascript error.

**Comment by barbequesauce** [comment]
Safari. Same results in OSX and iOS.

**Comment by nosmokingbandit** [comment]
058d6860db24e77d290ebcf1ebec8764f9517813

Safari handles select menus differently than other browsers for some reason. This commit should get everything working as expected.

**Comment by barbequesauce** [comment]
That fixed it - thanks!
