### ISSUE TITLE
Problem searching movie The 15:17 to Paris

### ISSUE THREAD

**Issue by bundyboss** [nosmokingbandit/Watcher3#173]
Hi,
I can't search movie "The 15:17 to Paris".
If I search on to paris I can found it.
Problem seems to be on the ":"
Regards

**Comment by nosmokingbandit** [comment]
You are right, the colon was making it search for 'the 1517 to paris'

3a872e29f764a1bbf91196a2e5e7ffa7119f63de fixes this.

**Comment by bundyboss** [comment]
I confirm that is working fine. (I've send you an email with another demand. Have you receive it?)
Thks
