### ISSUE TITLE
Failure while processing backlog (macOS, python 3.6.3)

### ISSUE THREAD

**Issue by Alrescha-git** [nosmokingbandit/Watcher3#174]
WARNING [2017-12-16 16:57:56,331] CPTaskScheduler._task.256: Scheduled Task Movie Search Failed:
Traceback (most recent call last):
  File "/Users/test/Downloads/Watcher3/core/cp_plugins/taskscheduler.py", line 254, in _task
    self.task()
  File "/Users/test/Downloads/Watcher3/core/searcher.py", line 151, in search_all
    self.search(imdbid, title, year, quality)
  File "/Users/test/Downloads/Watcher3/core/searcher.py", line 215, in search
    results[idx]['resolution'] = self.get_source(result)
  File "/Users/test/Downloads/Watcher3/core/searcher.py", line 399, in get_source
    if any(i in title.upper() for i in ('4K', 'UHD', '2160P')):
  File "/Users/test/Downloads/Watcher3/core/searcher.py", line 399, in <genexpr>
    if any(i in title.upper() for i in ('4K', 'UHD', '2160P')):
AttributeError: 'int' object has no attribute 'upper'

**Comment by nosmokingbandit** [comment]
Send me the log starting from the beginning of the post-processing request.

`watchernzb@gmail.com`

**Comment by Alrescha-git** [comment]
Sent

**Comment by nosmokingbandit** [comment]
9d36e96

The technical explanation:

The commit message is pretty verbose, but the culprit was a release with the title `163025` which the xmljson module parsed as an int rather than a string. The yahoo format in that module uses only strings, which makes it more predictable and easier to work with.

The simple explanation:

I fixed it.

**Comment by Alrescha-git** [comment]
I restored the problem database to a new installation and let it run through the backlog of movies.  No failures or warnings in the log.  Looking good.

**Comment by nosmokingbandit** [comment]
Cool beans. I'm going to close this, but feel free to open it back up if anything resurfaces.
