### ISSUE TITLE
Suggestion: Ignore unix dot (.) files during post-processing

### ISSUE THREAD

**Issue by Alrescha-git** [nosmokingbandit/Watcher3#175]
Watcher does not ignore unix hidden files while scanning the directory for post processing.  In my case that means that it picks up various .status files created by my downloader and tries to process them.

**Comment by nosmokingbandit** [comment]
It shouldn't think those files are movies since they are too small. Is it moving them along with extra files like subs?

**Comment by Alrescha-git** [comment]
I see in the logs that Watcher is trying to look them up in TheMovieDB, and they are getting renamed (which is the only thing I have post doing right now).

**Comment by nosmokingbandit** [comment]
Is this from a post-processing scan? I think that is the only method that might pick up those files. A pp request from your download client shouldn't cause this.

**Comment by Alrescha-git** [comment]
Yes, this is from the pp directory scan which I run hourly to pick up downloads.  I'll give the new build a try, thanks.

**Comment by Alrescha-git** [comment]
No more attempts to lookup and process . files after update.
