### ISSUE TITLE
Feature Request: API Additions

### ISSUE THREAD

**Issue by LeeThompson** [nosmokingbandit/Watcher3#179]
Some additional API commands would be useful:

shutdown  - cleanly shutdown Watcher
restart - restart Watcher
update - have Watcher update itself (if an update is available)
ping - ping Watcher (returns OK)
searchnow - start searching for a movie (if no imdbid is specified then start the full search queue) (syntax identical to liststatus)

**Comment by LeeThompson** [comment]
At the very least it would be nice if you could do:

`curl -s http://localhost:9191/system/shutdown`

and have it actually shut down (although requiring an API key, of course, would be a much better idea)

**Comment by barbequesauce** [comment]
+1

This functionality would be very helpful in automating certain types of maintenance...

**Comment by nosmokingbandit** [comment]
f30748d2ff8b09065fe36561fa15a13bf425757f

Use with `/api?apikey=APIKEY&mode=server_shutdown` and `/api?apikey=APIKEY&mode=server_restart`
