### ISSUE TITLE
Feature requests New status: Waiting to be released

### ISSUE THREAD

**Issue by PotatoQuality** [nosmokingbandit/Watcher3#18]
Right now we have the workflow:
Wanted>Found>Snatched>Finished

I like to have one more status: "Waiting" or something like "waiting to be released."
People can set a delay, it is nice to see if watching is still in the release state instead of showing for every requests "wanted".
Beceause, if you have something like this: its more clear what watcher is doing.

**Comment by nosmokingbandit** [comment]
There is an indication in the movie's status page if is has been found on predb yet, but it does make sense to make this part of the normal status chain.

It is on the to-do list.

**Comment by nosmokingbandit** [comment]
Added in https://github.com/nosmokingbandit/Watcher3/commit/e06daf6ede9d0659e22a134d0103ced556133f6a

The chain now goes Waiting>Wanted>Found>Snatched>Finished. Your library should automatically change Wanted to Waiting where appropriate after updating. On my testing server it seemed to take immediately, but on my main server it changed after running an rss sync. But that might be a weird browser caching thing, so I'm not going to worry too much about it.
