### ISSUE TITLE
WatcherPlugins sys.argv

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#181]
Looks like the values passed to plugins have changed. I'm not receiving the movie_dir final path anymore.

**Comment by jaketame** [comment]
Its def not passing the correct final destination path;

DEBUG [2017-12-22 14:56:55,202] core.plugins.execute.250: Executing plugin Plex Scan.py as ['/usr/bin/python3', '/config/plugins/fin                                                                ished/Plex Scan.py', 'Jack Frost', '1998', 'tt0141109', 'WebDL-1080P', 'None', '/data/downloads/movies/Jack.Frost.1998.1080p.AMZN.WE                                                                B-DL.DD+2.0.x264-monkee/Jack.Frost.1998.1080p.AMZN.WEB-DL.DD+2.0.x264-monkee.mkv', '/data/media/movies/Jack Frost (1998)/Jack.Frost.                                                                1998.1080p.AMZN.WEB-DL.DD+2.0.x264-monkee.mkv', '541', '2017-12-22', 'Default', '{"plexscan": ""}'].

**Comment by jaketame** [comment]
Looks like the correct folder path is given to plugins post processing however the filename is the original filename.

**Comment by nosmokingbandit** [comment]
c28d755e63ba730335d99aaffc9531bbfcaf139c

Aught to take care of this. I tested every combination I can think of, but please report back either way with your findings.

**Comment by jaketame** [comment]
Nice one. All sorted it seems! High five
