### ISSUE TITLE
question about post proccessing

### ISSUE THREAD

**Issue by valantislevas** [nosmokingbandit/Watcher3#184]
Hello is possible after a copy on post proccessing to put the movie and other files of release on specific folder?

now we put directory for movies and it works but if is possible to make a directory with same name of the movie title on folder name and put there the movie and his files..

thanks for the great work

**Comment by CanadianHammer** [comment]
That is specified within the 'Move Movies' option using tags

for example, "/movies/{year}/{title}/"

**Comment by nosmokingbandit** [comment]
I'm going to assume @CanadianHammer's answer was sufficient, so I'm closing this.
