### ISSUE TITLE
Issue parsing results from Jackett

### ISSUE THREAD

**Issue by cdonovan** [nosmokingbandit/Watcher3#186]
I've found that when a Jackett API call returns only a single "item" element, the search fails with the following error:

AssertionError
    assert(type(items) == list)
  File "/opt/Watcher3/core/providers/base.py", line 119, in parse_newznab_xml
Traceback (most recent call last):
ERROR [2018-01-03 17:54:25,180] root.parse_newznab_xml.121: Unexpected XML format from NewzNab indexer.

I verified that the XML coming from Jackett is valid, and it seems that this only happens when there is a single <item> being returned.  Not too familiar with python, but was thinking that maybe something happens when trying to cast the items to a list?

**Comment by barbequesauce** [comment]
This is happening to me periodically as well.

**Comment by nosmokingbandit** [comment]
What are you looking for that has only one result? Even the most obscure
movies I've tried have multiple results.

**Comment by barbequesauce** [comment]
In my case I could reproduce by searching for "Pokemon Arceus and the Jewel of Life" (TMDB ID 39057), returning "Pokemon.Arceus.and.the.Jewel.of.Life.2009.DUBBED.1080p.BluRay.x264-PHOBOS" from AR through Jackett/torznab..

**Comment by barbequesauce** [comment]
Looks good now, thanks.

**Comment by nosmokingbandit** [comment]
b9acf0232d13da9341fd211156f0b26b6f175fbe

I'll close this then. Thanks for reporting back.
