### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by j0hnsen** [nosmokingbandit/Watcher3#19]
What about some statistics we all love stats...
You have ZZZ movies in your library ( AA with status wanted, BB with status found ...)

Maybe it's possible to build something like this?

**Comment by nosmokingbandit** [comment]
I'm working on something like this. There are a few graphs I should be able to pull from the database to give you a good report.

**Comment by nosmokingbandit** [comment]
I added a few simple charts in 5d668514e7cf6af4bd955e12ac99646030f45977 under Status > Manage Library.

Let me know if there is something specific you want graphed and I'll see what I can do.

**Comment by j0hnsen** [comment]
Great job!

But now I see that watcher is a bit slow with 10k+ Movies :D
