### ISSUE TITLE
Sort by theatrical release / in cinemas ?

### ISSUE THREAD

**Issue by jbrodriguez** [nosmokingbandit/Watcher3#194]
I think theatrical release is available.

Not sure about in cinemas.

Is it a low/medium/high difficulty mod ?

I'd be willing to take a stab at a PR if low/medium.

**Comment by nosmokingbandit** [comment]
dafc0a512c6337e15553c57f2bf60c4337fb9b8c

This changes 'Year' to sort using full date rather than just the year. Before it would sort by Year, then whatever order they happened to already be in, so this change doesn't diminish the Year sort.
