### ISSUE TITLE
post proscessing

### ISSUE THREAD

**Issue by poplolnman** [nosmokingbandit/Watcher3#199]
Hi it seems that watcher will only process movies without a folder, when there is a foldered movie it just sits there. is this meant to work like that?

**Comment by oddsocksio** [comment]
am having the same issue

**Comment by nosmokingbandit** [comment]
Was this happening with client-triggered processing or the directory scanner?

be989807e230e6dce9bf47a1e2c670c0f0512378 fixed a few problems with the dir scanner.

**Comment by mrdeadlocked** [comment]
I have the same issue. Files have to be in the watched directory to get them post processed.

**Comment by barbequesauce** [comment]
Possible relationship with #215 (and possible fix there)?

**Comment by barbequesauce** [comment]
Late follow up on this - my situation is corrected with this fix...

**Comment by nosmokingbandit** [comment]
Cool beans, I'll close this then.
