### ISSUE TITLE
Update broke watcher

### ISSUE THREAD

**Issue by markusn1** [nosmokingbandit/Watcher3#202]
Hello. For the second time now, a recent update broke Watcher3. I am running Ubuntu 14.04.5 LTS with Python 2.7.12.

/opt/Watcher3/logs/log.txt:

> DEBUG [2018-02-03 09:05:24,760] core.version.pull.173: Pulling latest commit.
DEBUG [2018-02-03 09:05:24,760] core.version.runner.95: Executing Git command: ['git', 'pull']
INFO [2018-02-03 09:05:25,753] core.version.execute_update.225: Update successful.
INFO [2018-02-03 09:05:25,753] core.version.update_check.67: Update successful, restarting.
INFO [2018-02-03 09:05:25,753] cherrypy.error.error.219: [03/Feb/2018:09:05:25] ENGINE Bus STOPPING
INFO [2018-02-03 09:05:25,883] cherrypy.error.error.219: [03/Feb/2018:09:05:25] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9090)) shut down
INFO [2018-02-03 09:05:25,913] cherrypy.error.error.219: [03/Feb/2018:09:05:25] ENGINE Stopped thread 'Session cleanup'.
INFO [2018-02-03 09:05:25,918] cherrypy.error.error.219: [03/Feb/2018:09:05:25] ENGINE Bus STOPPED
INFO [2018-02-03 09:05:25,923] core.restart.76: Server stopped -- respawning script as:
 /usr/bin/python3 /opt/Watcher3/watcher.py

running /usr/bin/python3 /opt/Watcher3/watcher.py manually:

> Traceback (most recent call last):
  File "/opt/Watcher3/watcher.py", line 109, in <module>
    from core import config, scheduler, version
  File "/opt/Watcher3/core/scheduler.py", line 11, in <module>
    from core.rss import imdb, popularmovies
  File "/opt/Watcher3/core/rss/imdb.py", line 84
    self.searcher.search(*i, core.config.default_profile())
                                            ^
SyntaxError: only named arguments may follow *expression

**Comment by barbequesauce** [comment]
Same here.

**Comment by barbequesauce** [comment]
Looks like this afternoon’s commit fixed it, thanks.

**Comment by nosmokingbandit** [comment]
Certain python versions lack certain features that the latest version has. I'm usually pretty good about catching them, but sometimes one slips by.
