### ISSUE TITLE
"Unable to complete update."

### ISSUE THREAD

**Issue by LeeThompson** [nosmokingbandit/Watcher3#206]
```
ERROR [2018-02-08 11:32:20,430] core.ajax.update_server.453: Update Failed.
ERROR [2018-02-08 11:32:20,430] core.version.execute_update.222: Update failed: fatal: unable to access 'https://github.com/nosmokingbandit/Watcher3.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
INFO [2018-02-08 11:32:19,567] core.version.execute_update.209: Updating from Git.
```

This may be a github issue because I get the same error from the command line:

`fatal: unable to access 'https://github.com/nosmokingbandit/Watcher3.git/': error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version`

**Comment by LeeThompson** [comment]
Updated my Git installation and now it's fine.

**Comment by nosmokingbandit** [comment]
Heh, that's weird. At least it was an easy fix. I haven't updated Git since I installed it a long time ago. One of those things I never think about.

**Comment by LeeThompson** [comment]
Same, I left the issue up here tho just in case someone else has the same problem.
