### ISSUE TITLE
Request improve Black Hole for magnet link.

### ISSUE THREAD

**Issue by balaios** [nosmokingbandit/Watcher3#207]
Caching site (like itorrents) not work in most cases.
#80 

Python 3.6.4

> WARNING [2018-02-09 01:22:08,101] root.open.87: Error code 404 in response from http://btdig.com/torrent/4D8AB99725E5C40503F381DB0EE055374A24BE7D.torrent
> DEBUG [2018-02-09 01:22:08,101] root.get_hash.148: Finding hash for torrent b'Found Nothing'
> ERROR [2018-02-09 01:22:08,101] root.get_hash.158: Unable to get torrent hash
> Traceback (most recent call last):
>   File "/home/ivan/Projetos/Watcher3/core/helpers.py", line 154, in get_hash
>     metadata = bencodepy.decode(raw)
>   File "/home/ivan/Projetos/Watcher3/lib/bencodepy/decoder.py", line 100, in decode
>     return decoder.decode()
>   File "/home/ivan/Projetos/Watcher3/lib/bencodepy/decoder.py", line 55, in decode
>     return self.__wrap_with_tuple()
>   File "/home/ivan/Projetos/Watcher3/lib/bencodepy/decoder.py", line 63, in __wrap_with_tuple
>     l.append(self.__parse())
>   File "/home/ivan/Projetos/Watcher3/lib/bencodepy/decoder.py", line 50, in __parse
>     'Invalid token character ({0}) at position {1}.'.format(str(char), str(self.idx)))
> bencodepy.exceptions.DecodingError: "Invalid token character (b'F') at position 0."

> WARNING [2018-02-09 01:22:08,101] core.downloaders.BlackHole._download_magnet.153: Torrent hash 4D8AB99725E5C40503F381DB0EE055374A24BE7D not found on any torrent cache.
> ERROR [2018-02-09 01:22:08,101] core.downloaders.BlackHole.add_torrent.118: Could not download Torrent.

[log.txt](https://github.com/nosmokingbandit/Watcher3/files/1709755/log.txt)

**Comment by nosmokingbandit** [comment]
Nothing I can do about that. In order to download a magnet to a blackhole directory it must first be resolved to a .torrent file. If cache sites don't have it available there is nothing to download.

**Comment by balaios** [comment]
All right then.

But even finding hash for torrent (https://itorrents.org/) does not work

> INFO [2018-02-09 01:22:03,699] core.downloaders.BlackHole._download_magnet.140: Attempting to resolve torrent hash through https://itorrents.org/torrent/4D8AB99725E5C40503F381DB0EE055374A24BE7D.torrent
> DEBUG [2018-02-09 01:22:04,982] root.get_hash.148: Finding hash for torrent b'....'

> WARNING [2018-02-09 01:22:08,101] core.downloaders.BlackHole._download_magnet.153: Torrent hash 4D8AB99725E5C40503F381DB0EE055374A24BE7D not found on any torrent cache.
> ERROR [2018-02-09 01:22:08,101] core.downloaders.BlackHole.add_torrent.118: Could not download Torrent.

[log.txt](https://github.com/nosmokingbandit/Watcher3/files/1709755/log.txt)

**Comment by nosmokingbandit** [comment]
You probably noticed that in 3f10d7173e50c4a7907dc6d5c236e322b09e9fb9 I added magnet2torrent as a source to resolve magnets since they seem to have a pretty thorough database. While doing this I optimized the rest of the code and made things a little smoother. Let me know if this has any noticeable effect for you.

**Comment by balaios** [comment]
Yes, thank you. now it's working very well.
