### ISSUE TITLE
No results returned though log says "will include in search"

### ISSUE THREAD

**Issue by ben-joostens** [nosmokingbandit/Watcher3#218]
This is part of the log file after manually searching for a movie that should return results but doesn't.

```
INFO [2018-02-18 22:45:10,164] core.searcher.get_source.414: Source media determined as DVD-SD
INFO [2018-02-18 22:45:10,165] core.searchresults.score.37: Scoring 6 search results.
INFO [2018-02-18 22:45:10,166] core.searchresults.remove_ignored.115: Filtering Ignored Words.
INFO [2018-02-18 22:45:10,167] core.searchresults.remove_ignored.130: Keeping 6 results.
INFO [2018-02-18 22:45:10,167] core.searchresults.retention_check.181: Checking retention.
INFO [2018-02-18 22:45:10,167] core.searchresults.retention_check.195: Keeping 6 results.
INFO [2018-02-18 22:45:10,167] core.searchresults.seed_check.206: Checking torrent seeds.
INFO [2018-02-18 22:45:10,167] core.searchresults.seed_check.217: Keeping 5 results.
INFO [2018-02-18 22:45:10,167] core.searchresults.freeleech.225: Adding Freeleech points.
INFO [2018-02-18 22:45:10,167] core.searchresults.score_sources.343: Filtering resolution and size requirements.
INFO [2018-02-18 22:45:10,168] core.searchresults.score_sources.381: Keeping 4 results.
INFO [2018-02-18 22:45:10,168] core.searchresults.score_preferred.244: Scoring Preferred Words.
INFO [2018-02-18 22:45:10,168] core.searchresults.score.87: Finished scoring search results.
INFO [2018-02-18 22:45:10,169] core.searcher.store_results.368: 4 results found for tt1234567. Storing results.
INFO [2018-02-18 22:45:10,170] core.searcher.store_results.378: Storing backlog search results -- purging existing results before writing to database.
INFO [2018-02-18 22:45:10,175] core.library.movie_status.907: Determining appropriate status for movie tt1234567.
INFO [2018-02-18 22:45:10,177] core.searcher.verify.79: Awesome Movie passes verification checks, will include title in search.
```
As far as I understand from this log, this means that there are results that pass all the filters. I've also manually searched jackett and that seems to confirm that there are viable candidates. However, since the log doesn't tell me why I'm not getting any results, it makes it hard to figure out why they're being omitted.

I've also tried a new quality profile which removes most filtering options, but to no avail.

**Comment by nosmokingbandit** [comment]
Enable debug logging if you want to see more detail. I can't tell much from
that tiny log segment.

**Comment by UnR34L** [comment]
I'm having the same issue, it seems to find it but does not show in the UI.

https://pastebin.com/raw/L9zwZqMB

**Comment by nosmokingbandit** [comment]
fbf95ef30fdc965992422bea2abd7646f307039b

This seems to occur only with newz/torznab indexers when imdb search isn't supported. I don't use any torznab indexers, so I tested this fix with a public tracker in Jackett and it resolved the problem for me. Let me know if it corrects things on your end.

**Comment by ben-joostens** [comment]
I'll try to find some time to test this again, I wasn't able to reproduce it lately.

**Comment by UnR34L** [comment]
@nosmokingbandit 

So, I deleted my comment because I left watcher running for a few days and it suddenly picked something up, so I thought I would do some more research when I had the time.

It seems that when ever I force a search or when I initially add something, nothing comes up and I get the glaring error message "will include in search"

But here's the debug log for https://github.com/nosmokingbandit/Watcher3/commit/fbf95ef30fdc965992422bea2abd7646f307039b - [logs.txt](https://pastebin.com/raw/UWKNENR2)

**Comment by UnR34L** [comment]
@nosmokingbandit 

Ok, I just tried 4 different releases, all of which I know are available, named correctly, using a quality that's in the default profile, were just recently added with plenty of seeds, 2 worked, 2 didnt. So I'm not sure what it's doing.

@ben-joostens said he couldn't reproduce it, guessing he tried some different releases and they worked.

**Comment by nosmokingbandit** [comment]
I've seen the error in your most recent logs before, and I think it is when Jackett only returns one search result. It doesn't format the xml according to newznab spec, so there are already tons of exceptions in place for its flavor of newznab xml.

All releases are supposed to be inside `<item></item>` tags, so if there are not child `<item>` elements there are no releases being returned from Jackett.

**Comment by nosmokingbandit** [comment]
There was some bugs in handling imdb id numbers. Can you check if this still occurs after https://github.com/nosmokingbandit/Watcher3/commit/fd8279568095ce875fa4f3e5cec67e917f1bcd72 ?

**Comment by enilfodne** [comment]
Seems to work fine for me, though it seems something wonky is happening as a `FreeLeech` torrent was put before a `newzNAB` result.
