### ISSUE TITLE
core/helpers.py Url. normalize not support chinese

### ISSUE THREAD

**Issue by happyeddie** [nosmokingbandit/Watcher3#222]
chinese char will convert to empty

**Comment by happyeddie** [comment]
s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')

replace 'ascii' to 'utf-8'

**Comment by nosmokingbandit** [comment]
Urls cannot contain unicode characters.

This is related to #223, so I'm closing this.
