### ISSUE TITLE
Feature Request Block or lock the backend of Watcher

### ISSUE THREAD

**Issue by DraZtiK** [nosmokingbandit/Watcher3#225]
This is not an issue but a request to allow normal access to the frontend (Library, Add Movie) but lock, block or password the backend (Settings) to prevent normal users from viewing account info or keys for other websites/account?

Something like a user login and an admin login?

**Comment by DraZtiK** [comment]
Yes exactly, I allow others to add movies but they don't need nor do I want them to mess with or view the settings.

**Comment by nosmokingbandit** [comment]
I just pushed 14e78f00c1b58ed3722490cdafef6586d70ed951, which does this.

In settings/server you can require an admin account to access anything in settings/, regardless of the password settings for the entire UI.

**Comment by DraZtiK** [comment]
works great! Thank you!
