### ISSUE TITLE
Searching Issue

### ISSUE THREAD

**Issue by deldran** [nosmokingbandit/Watcher3#232]
** Commit: I believe I am on the latest version.  I am running it through a docker
** Operating System: Docker/Ubuntu16.04
** Python Version [python -V]: Docker version
** What happened: Not searching peroperly

I use IPtor as my tracker, and i utilize Jackett to make a torznab link for it to search through.  I know the movie i added is available, but watcher says nothing is available.  Radarr finds it without issue with the same indexer setup.

Edited by @nosmokingbandit
* removed logfile with release names to keep those who may be concerned happy
* log file contained exceptions related to self.imdbid calls in newznab base class

**Comment by nosmokingbandit** [comment]
May be related to #218 and commit fbf95ef30fdc965992422bea2abd7646f307039b

Can you confirm if this is still occurring after this update?

**Comment by nosmokingbandit** [comment]
Cool beans, I'll close this then.
