### ISSUE TITLE
Plex Import ends in 500 server error

### ISSUE THREAD

**Issue by barbequesauce** [nosmokingbandit/Watcher3#239]
** Commit: 9b1a3570bc005f97be1b20d6ab80d6f6f82bbf41
** Operating System: Raspbian Jessie
** Python Version [python -V]: 2.7.9
** What happened: Attempting to import Plex csv created by ExportTools... HTTP error 500. Several tracebacks in the attached logs.
** Logs:
[log.pleximport.txt](https://github.com/nosmokingbandit/Watcher3/files/1873827/log.pleximport.txt)

**Comment by nosmokingbandit** [comment]
Would you mind emailing me your csv? The log shows that the `Title` column is missing and I'm not sure why that would be the case.

`watchernzb@gmail.com`

**Comment by barbequesauce** [comment]
Sorry, not sure how I missed this - I’ll send it now.

**Comment by nosmokingbandit** [comment]
I just started looking into this and the first thing I noticed is your csv is named `Movies-Level2-xxxxxxx.csv` which probably means you didn't set the export level to 5. Level 5 export is required so it includes file information as well as the movie metadata/

This doesn't completely answer why the `Title` key isn't found, but I think that might have to do with 93068f8be8b49702a80399df7878472f6d991e9f.

**Comment by barbequesauce** [comment]
Thanks - I missed the level 5 part of the instructions.

I did an update this morning and tried again with a fresh export - I'm still getting the below error. I'll send the export and the full log to your email momentarily.

```
ERROR [2018-04-17 11:04:58,063] core.library.read_csv.258: Error parsing Plex CSV.
   3648 Traceback (most recent call last):
   3649   File "/opt/Watcher3/core/library.py", line 198, in read_csv
   3650     logging.info('Parsing Plex movie {}'.format(movie['Title']))
   3651 KeyError: 'Title'
```

**Comment by nosmokingbandit** [comment]
This was a parsing problem due to me assuming everyone uses a comma for csv. I've got a fix but I want to test it a bit before I push it out and it is already well past my bed time. Thanks for the emails, it helps a lot.

**Comment by barbequesauce** [comment]
Much more better. Thank you as always!

**Comment by nosmokingbandit** [comment]
How did your browser handle the import? There is probably a bit more optimization to be found, but I don't want to spend the time on it if it was just my computer being stupid.

**Comment by barbequesauce** [comment]
Safari on macOS... no issue at all with the big file. Whole operation took less time than looking up imdb id's for ten movies...
