### ISSUE TITLE
Minor typo in movie detail popup

### ISSUE THREAD

**Issue by LeeThompson** [nosmokingbandit/Watcher3#248]
If a film hasn't been found yet, the following text appears at the bottom of the film's "detail" popup:

`Nothing found yet. Next search sheduled for {DATE} at {TIME}.`

It should read:

`Nothing found yet. Next search scheduled for {DATE} at {TIME}.`

**Comment by nosmokingbandit** [comment]
I wonder if vscode has a spell checker...

5a8f321d6cdf45c2f23aaea6d7706c3a71b7723c

Thanks.
