### ISSUE TITLE
ImportError: cannot import name 'searcher'

### ISSUE THREAD

**Issue by CaptainConsternant** [nosmokingbandit/Watcher3#249]
Before submitting an issue...

* Enable debug logging in settings/server.

* Repeat the actions required to reproduce the error.

Provide all information requested below. Issues without adequate information will be closed without response.

** Commit: a6eda252958080da21369e048a31cbe6dedf0709
** Operating System: amrbian 
** Python Version [python -V]:Python 2.7.9
** What happened:
crash at startup

** Logs:
If logs contain information you do not wish to share with the world you may email them to `watchernzb@gmail.com`. Include the issue number in the subject line of the message.
```
PASTE LOGS HERE
python3 ./watcher.py -d

WARNING:root:Unable to set locale. Date parsing may not work correctly.
 Unable to set locale. Date parsing may not work correctly.
Connected to database sqlite:////xxxxxxxxxxxxxxxxxx/watcher.sqlite
Config file found, merging any new options.
Clearing Mako cache.
Traceback (most recent call last):
  File "./watcher.py", line 107, in <module>
    from core import config, scheduler, version
  File "/xxxxxxxxxx/Watcher3/core/scheduler.py", line 10, in <module>
    from core import searcher, postprocessing
  File "/xxxxxxxxxxxxxxxx/Watcher3/core/searcher.py", line 5, in <module>
    from core import searchresults, snatcher, proxy
  File "/xxxxxxxxxxxxx/Watcher3/core/snatcher.py", line 8, in <module>
    from core.library import Manage
  File "/xxxxxxxxxxx/Watcher3/core/library.py", line 7, in <module>
    from core import searchresults, plugins, searcher
ImportError: cannot import name 'searcher'
 alex@raspberrypi:~/Mxxxxxxxx/Watcher3$ git pull
Already up-to-date.


```

**Comment by CaptainConsternant** [comment]
git checkout 6f5fb32a37ee40ddecaca2575bc1ee2be1e053a8
makes it work again.

Thanks

**Comment by nosmokingbandit** [comment]
Should be ok as of fc1b4010351887704ecfc045b54046b158b227e5. Different versions of python 3 handle local imports differently (because why not?) and this fixes it. I've just switched my dev environment over to 3.4 so I can catch these before committing them next time.

**Comment by CaptainConsternant** [comment]
Yes it works now 

Thanks ! :+1:
