### ISSUE TITLE
Unable to finish download with sab

### ISSUE THREAD

**Issue by poplolnman** [nosmokingbandit/Watcher3#25]
Hi,

I keep getting this error from sab when it tries to download a movie sent to it by watcher:

Traceback (most recent call last):
  File "C:\Program Files\SABnzbd\scripts\sabnzbd.py", line 22, in <module>
    import urllib.request
ImportError: No module named request

**Comment by PotatoQuality** [comment]
You need te  python module  request

**Comment by poplolnman** [comment]
what is that?

**Comment by PotatoQuality** [comment]
https://www.google.nl/?gws_rd=ssl#safe=off&q=python+requests+module

**Comment by PotatoQuality** [comment]
Your python library is missing the module "request"". You need to download and install it manualy.

**Comment by nosmokingbandit** [comment]
It looks like Sab is attempting to run the script with python 2 rather than 3.

You do not need any extra modules -- the post processing scripts were designed to work with just the standard library.

Their docs aren't super clear about it, but it seems that Sab runs scripts using the bundled python build rather than calling the system's python.

I've reverted the post-script back to a 2.7 compatible version. Update to 34d67e8a9ee722fab3715aac40d8a0f324f31999, then copy your post-script back to Sab.

**Comment by PotatoQuality** [comment]
@nosmokingbandit wait are you sure? when installed the request module on my server i was able to run it?

**Comment by nosmokingbandit** [comment]
The requests module has nothing to do with urllib.request

**Comment by poplolnman** [comment]
hi,

while it does import my movie now, it just named the movie "john wick" to xyz.mkv and here is the error message: 

Sending john%20wick%202014%20720p%20bluray%20dts%20x264%20legi0n to Watcher as Complete.
Traceback (most recent call last):
  File "C:\Program Files\SABnzbd\scripts\sabnzbd.py", line 69, in <module>
    response = json.loads(urllib2.urlopen(request, timeout=600).read())
  File "C:\Python27\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 500: Internal Server Error

**Comment by nosmokingbandit** [comment]
That indicates something went wrong on the Watcher side. Send me the log starting with the 'Post Processing Request' line

watchernzb@gmail.com
