### ISSUE TITLE
cannot marshal None unless allow_none is enabled

### ISSUE THREAD

**Issue by RicRock** [nosmokingbandit/Watcher3#255]
Trying to add a movie to my library and receive the error message as in the title.

Log text emailed

$ python3 -V
Python 3.6.3

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful

**Comment by nosmokingbandit** [comment]
Without debug logging it is hard to know what is happening. Enable debug logging (settings/server), restart Watcher, and try again. Then send me the logs.

**Comment by RicRock** [comment]
Seems to be working currently.

Thanks!
