### ISSUE TITLE
[REQUEST] UI Scaling

### ISSUE THREAD

**Issue by xGBHxPegasus** [nosmokingbandit/Watcher3#256]
Been using Watcher3 for a few days now and loving it so far since moving over from CP. One thing I have noticed (not an issue btw) is that the UI seems to centre a lot like a facebook feed. 

Would it be possible to maybe add extra layouts in to use the screen more? (Blurred out the main bit)
![screenblur](https://user-images.githubusercontent.com/11061794/42409068-7a6e228a-81cc-11e8-947e-82dbad9554ca.png)

Definitely not an issue and not urgent at all but would be nice if possible, a bit like how plex does it :)

Thanks for all the great work so far!

**Comment by nosmokingbandit** [comment]
I've kind of wanted to do this for a while but it requires some css trickery to get everything working correctly and I've procrastinated long enough.

Done in https://github.com/nosmokingbandit/Watcher3/commit/c9d90ad460c89a66244f541ba33e760ae0fbfad0

**Comment by xGBHxPegasus** [comment]
Awesome! Thanks for making the change so quickly 👍

**Comment by nosmokingbandit** [comment]
I'll close this then. I've been mostly working on other projects, so having a break to get back to this was somewhat welcome.
