### ISSUE TITLE
[Request] Cleaning out library and removing non existing items

### ISSUE THREAD

**Issue by UnR34L** [nosmokingbandit/Watcher3#258]
Is there a way to remove old junk items without having to go through it all and manually removing ?
From what I can see there's no indication in library view if the item has a file on disk.

To maintain large libraries over time we need a way to see (at least) and remove old junk items. Ideally a feature that checked the database for stale items would be amazing.

**Comment by nosmokingbandit** [comment]
Depends on what you mean by "junk."

You can go into library/manage and select movies based on quality profile
or status and remove them in bulk there.

**Comment by UnR34L** [comment]
>non existing items

Delete a bunch of files, it's a decent sized library, how would I go about removing that stuff from watcher ?

If it showed the status (if there's a file for that item) in watcher, I could see that and bulk remove them.

**Comment by nosmokingbandit** [comment]
Added in 
9a6d136.

See settings/system to configure.

**Comment by UnR34L** [comment]
Waiting on https://github.com/nosmokingbandit/Watcher3/issues/264 before I can test.

**Comment by UnR34L** [comment]
I'm getting hit with errors, turned on debugging, this is the relevant entries.

> INFO [2018-07-29 18:11:00,043] core.ajax.manual_task_execute.1326: Manually executing task Missing Files Scan.
> INFO [2018-07-29 18:11:00,043] CPTaskScheduler._task.248: == Executing Task: Missing Files Scan Per User Command ==
> DEBUG [2018-07-29 18:11:00,047] core.sqldb.execute.156: Executing SQL command: ['SELECT * FROM MOVIES WHERE finished_file is not null']
> WARNING [2018-07-29 18:11:00,049] CPTaskScheduler._task.266: Scheduled Task Missing Files Scan Failed:
> Traceback (most recent call last):
>   File "/usr/local/Watcher3/lib/cherrypyscheduler.py", line 264, in _task
>     self.task()
>   File "/usr/local/Watcher3/core/library.py", line 718, in scanmissingfiles
>     movies = core.sql.proxy_to_dict(movies)
> AttributeError: 'SQL' object has no attribute 'proxy_to_dict'
> DEBUG [2018-07-29 18:11:00,053] core.sqldb.row_exists.580: Checking if name="Missing Files Scan" exists in database table TASKS
> DEBUG [2018-07-29 18:11:00,053] core.sqldb.execute.156: Executing SQL command: ['SELECT 1 FROM TASKS WHERE name="Missing Files Scan"']
> DEBUG [2018-07-29 18:11:00,055] core.sqldb.update.235: Updating last_execution to 2018-07-29 18:11:00 for rows that match name:Missing Files Scan in TASKS.
> DEBUG [2018-07-29 18:11:00,056] core.sqldb.execute.156: Executing SQL command: ['UPDATE TASKS SET last_execution=? WHERE name=?', ('2018-07-29 18:11:00', 'Missing Files Scan')]
> INFO [2018-07-29 18:11:00,062] CPTaskScheduler._task.273: == Finished Task: Missing Files Scan ==
> INFO [2018-07-29 18:11:06,886] core.ajax.get_log_text.512: Dumping log file log.txt to text.

Thanks for working on this.

**Comment by nosmokingbandit** [comment]
Should be working as expected in 0d99d981b1f361f0422218ee7b46885e796bed4a

Just a careless error on my part, easy enough to correct. Let me know if
this gives the results you were looking for.

**Comment by UnR34L** [comment]
Works great, thanks!
