### ISSUE TITLE
AutoUpdate fails

### ISSUE THREAD

**Issue by RicRock** [nosmokingbandit/Watcher3#259]
$ python3 -V
Python 3.6.3

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description: Ubuntu 17.10
Release: 17.10
Codename: artful

log file:

INFO [2018-07-15 09:08:32,951] core.ajax.update_server.435: Update process started.
INFO [2018-07-15 09:08:32,952] CPTaskScheduler.stop.295: Stopping scheduled task Movie Search.
INFO [2018-07-15 09:08:32,952] CPTaskScheduler.stop.295: Stopping scheduled task Update Checker.
INFO [2018-07-15 09:08:32,953] CPTaskScheduler.stop.295: Stopping scheduled task Metadata Update.
INFO [2018-07-15 09:08:32,954] core.version.execute_update.209: Updating from Git.
DEBUG [2018-07-15 09:08:32,955] core.version.fetch.163: Fetching latest Git info.
DEBUG [2018-07-15 09:08:32,955] core.version.runner.95: Executing Git command: ['git', 'fetch']
DEBUG [2018-07-15 09:08:35,511] core.version.pull.173: Pulling latest commit.
DEBUG [2018-07-15 09:08:35,512] core.version.runner.95: Executing Git command: ['git', 'pull']
ERROR [2018-07-15 09:08:38,065] core.version.execute_update.222: Update failed: error: Your local changes to the following files would be overwritten by merge:
        logs/log.txt
        templates/cache/templates/404.html.py
        templates/cache/templates/add_movie.html.py
        templates/cache/templates/head.html.py
        templates/cache/templates/library/import.html.py
        templates/cache/templates/library/import/couchpotato.html.py
        templates/cache/templates/library/import/directory.html.py
        templates/cache/templates/library/import/kodi.html.py
        templates/cache/templates/library/import/plex.html.py
        templates/cache/templates/library/manage.html.py
        templates/cache/templates/library/stats.html.py
        templates/cache/templates/library/status.html.py
        templates/cache/templates/login.html.py
        templates/cache/templates/navbar.html.py
        templates/cache/templates/settings/downloader.html.py
        templates/cache/templates/settings/indexers.html.py
        templates/cache/templates/settings/logs.html.py
        templates/cache/templates/settings/plugins.html.py
        templates/cache/templates/settings/postprocessing.html.py
        templates/cache/templates/settings/quality.html.py
        templates/cache/templates/settings/search.html.py
        templates/cache/templates/settings/server.html.py
        templates/cache/templates/settings/system.html.py
        templates/cache/templates/system/restart.html.py
        templates/cache/templates/system/shutdown.html.py
        templates/cache/templates/system/update.html.py
Please commit your changes or stash them before you merge.
Aborting
Updating 2d08448..c9d90ad
ERROR [2018-07-15 09:08:38,066] core.ajax.update_server.452: Update Failed.
INFO [2018-07-15 09:08:38,067] CPTaskScheduler.restart.338: Restarting schduled task Movie Search
INFO [2018-07-15 09:08:38,068] CPTaskScheduler.restart.338: Restarting schduled task Update Checker
INFO [2018-07-15 09:08:38,069] CPTaskScheduler.restart.338: Restarting schduled task IMDB Sync
INFO [2018-07-15 09:08:38,070] CPTaskScheduler.restart.338: Restarting schduled task Metadata Update
INFO [2018-07-15 09:08:38,071] CPTaskScheduler.restart.338: Restarting schduled task PopularMovies Sync
INFO [2018-07-15 09:08:38,072] CPTaskScheduler.restart.338: Restarting schduled task PostProcessing Scan
INFO [2018-07-15 09:08:38,072] CPTaskScheduler.restart.338: Restarting schduled task Trakt Sync

Any guidance appreciated!

**Comment by xGBHxPegasus** [comment]
I had the same when manually updating as the "click here to update" kept failing for me.

The main issue in this is the message I believe is: **Please commit your changes or stash them before you merge.**

How I got around it was by running the following in python:

1. Run 'git stash' (do this before attemping the update, it may ask to create a user or something but gives you the commands to do this).
2. Run the update
3. Run 'git stash pop'

This allowed me to manually update and worked fine.

(All the commands from above come from this thread, and probably explains it better: https://stackoverflow.com/questions/15745045/how-do-i-resolve-git-saying-commit-your-changes-or-stash-them-before-you-can-me).

**Comment by RicRock** [comment]
Worked for update.

Thanks!

**Comment by nosmokingbandit** [comment]
I was trying out SourceTree and for no reason at all decided to start tracking those files even though they are set in the .gitignore.

I think it should be ok going forward since I went back in and instructed it to *stop* tracking those files again, but let me know if anything else throws an error.
