### ISSUE TITLE
qbittorrent post-processing

### ISSUE THREAD

**Issue by poplolnman** [nosmokingbandit/Watcher3#26]
i have tried to download several movies and each time when they complete, they are not moved to my movie folder. Here is the last log entry in qbittorrent for it:

(N) 2017-04-22T23:59:59 - Torrent: A.Movie's.Title.2017, running external program, command: C:\Program Files\SABnzbd\scripts\qbittorrent.py&quot;A.Movie's.Title.2017&quot; &quot;J:\Downloads\Watcher\&quot; &quot;J:\Downloads\Watcher\A.Movie's.Title.2017&quot; &quot;e40b2dfdf8e080db7c96c43c40ad69b376243efe&quot;
 
there are no log entries in the watcher logs whatsoever for this as well.

*Edited for content by @nosmokingbandit

**Comment by poplolnman** [comment]
what additional info do you need as it is not post processing with qbittorrent whatsoever.

**Comment by nosmokingbandit** [comment]
It looks like there is no space between the script and the arguments.

`\qbittorrent.py"A.Movie's.Name`

should look like

`\qbittorrent.py"A.Movie's.Name`

Make sure all of the %X arguments in Qbitorrent are separated with a single space.
