### ISSUE TITLE
Endless Postprocessing 

### ISSUE THREAD

**Issue by sinopsysHK** [nosmokingbandit/Watcher3#260]
** Commit: c9d90ad460c89a66244f541ba33e760ae0fbfad0
** Operating System: windows 10 Home 64bit
** Python Version [python -V]: 3.5.1

Actually there are 2 issues (one being consequence of the other):

1/ when downloading a file not via Watcher in monitored directory then the file is processed at each scheduled postprocessing no matter that it was properly managed the first time: I have not set "Clean up download dir" nor "only process new files"

I investigated a bit a figured out that there could be inconsistency in the GUID computed from directory name as it is first used in upper case (scheduler.py line 119) but it is then turned to lower case (line 479 in postprocessing.py)  when completed saves status in DB thus when second postprocessing starts again it does not find the GUID and do all the metadata seeking again and then the mover + renamer
I've tried shortly to patch the postprocessing start turning GUID to lower case at the earliest (I added in core/postprocessing.py line 480 "data['guid'] = data['guid'].lower()") then it find back the previous run results and retrieve metadata from local but still performs complete task doing again mover + renamer without check if status wasn't already set to "Finished".

2/ consequence of doing again mover then renamer is that at the end I have two files in target directory: one with original file name and second with renamed one.
I would have assumed that it was because renamer after mover failed as the target renamed file already exists but I have no ERROR log telling so as expected according to lines 698 of postprocessing.py

**Comment by sinopsysHK** [comment]
In the Wiki I read:
“
Only Process New Files

When enabled, only files added since the last scan will be processed. This should remain disabled unless you have Move Movies disabled under Postprocessing.
“

May I understand that what I described is an expected behaviour to intentionally reprocess any existing previous files until they are removed from download directory ?

**Comment by nosmokingbandit** [comment]
Regardless of the GUIDs not matching (which should be corrected), it will still attempt to process any files that it can based on your config.  If you want to leave files in their downloaded directory you'll need to adjust your config to only process new files.

This is because sometimes you will need to process a file that Watcher already thinks is finished and having it reject this request could create more problems.

**Comment by sinopsysHK** [comment]
Hi,

Thank you for confirming my later understanding.
