### ISSUE TITLE
After update: nzbget.py PP error: nzbget: Import Error with urllib.parse

### ISSUE THREAD

**Issue by frodo2015** [nosmokingbandit/Watcher3#27]
Did an update today.

[https://github.com/nosmokingbandit/watcher3/compare/66cfaffc3bef36185717817ce37dbcc7b0d6e423...f413f3989d0871a4f8f86d54194deb4b0c7892fb](url)

I received some PP errors in nzbget 18.1.

`nzbget: Traceback (most recent call last):
nzbget: File "<frozen importlib._bootstrap>", line 2218, in _find_and_load_unlocked
nzbget: AttributeError: 'module' object has no attribute '__path__'
nzbget: During handling of the above exception, another exception occurred:
nzbget: Traceback (most recent call last):
nzbget: File "/home/nzbget/scripts/nzbget.py", line 37, in <module>
nzbget: import urllib.parse.urlencode as urlencode
nzbget: ImportError: No module named 'urllib.parse.urlencode'; 'urllib.parse' is not a package
Post-process-script scripts/nzbget.py for XXXXXXXXX failed (terminated with unknown status)`

pip search urlparse output.
`pip search urlparse
giturlparse.py (0.0.5)  - A Git URL parsing module (supports parsing and rewriting)
murl (0.5.1)            - murl is a tiny wrapper for the Python module urlparse.
uritools (2.0.0)        - RFC 3986 compliant, Unicode-aware, scheme-agnostic replacement for urlparse
urlparse2 (1.1.1)       - urlparse for humans.
urlparse3 (1.1)         - urlparse3 is simple and powerful url parsing tool
urlparse4 (0.1.3)       - Performance-focused replacement for Python's urlparse module`

Installed python 2.7.9 and python 3.4 on Debian Jessie.

**Comment by nosmokingbandit** [comment]
Stupid mistake on my part.

353d5dfe6047be0979f5dbe7d77b9003103a8af2 fixes post-scripts again (for good, I hope).

**Comment by j0hnsen** [comment]
Hmm got an error...
INFO 2017-04-24 20:45:49,693 core.postprocessing.get_movie_info: Movie data found locally by imdbid.
ERROR 2017-04-24 20:45:49,701 cherrypy.error.139726724848440.error: [24/Apr/2017:20:45:49] HTTP 
Traceback (most recent call last):
  File "/root/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/root/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/root/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/root/watcher/core/postprocessing.py", line 82, in POST
    data.update(self.get_movie_info(data))
  File "/root/watcher/core/postprocessing.py", line 223, in get_movie_info
    data.update(self.metadata.get_metadata(data['movie_file']))
KeyError: 'movie_file'
INFO 2017-04-24 20:45:49,702 cherrypy.error.139726724848440.error: [24/Apr/2017:20:45:49] HTTP 
Request Headers:
  Content-Length: 302
  ACCEPT-ENCODING: identity
  Content-Type: application/x-www-form-urlencoded
  Remote-Addr: 127.0.0.1
  HOST: 127.0.0.1:9090
  CONNECTION: close
  USER-AGENT: Mozilla/5.0

**Comment by nosmokingbandit** [comment]
That's a different error altogether, and I'm rather confused by that one.

This issue is resolved if we are getting this far, so I've opened a new issue to track the KeyError.

https://github.com/nosmokingbandit/Watcher3/issues/31
