### ISSUE TITLE
Unable to set api key in nzbget

### ISSUE THREAD

**Issue by PotatoQuality** [nosmokingbandit/Watcher3#29]
The field for the api key is gone after last update :(

![image](https://cloud.githubusercontent.com/assets/2944704/25352498/7bb34c0a-292c-11e7-996f-a94e159efdf7.png)

**Comment by PotatoQuality** [comment]
fixed https://github.com/nosmokingbandit/Watcher3/commit/c333b7a84f0c53f4afbd49a0e07af37583f98656

**Comment by nosmokingbandit** [comment]
Thanks for closing this, I forgot. I was playing with an automatic code formatter and it took away the single space after the `#` and NZBGet doesn't like that.
