### ISSUE TITLE
AttributeError: 'module' object has no attribute '_create_unverified_context'

### ISSUE THREAD

**Issue by OldMike** [nosmokingbandit/Watcher3#3]
Hi,

You closed the other issue so I repost it here.

Just cloned this new repo and got another error.
Debian Jessie - Python 3.4.2

```
/usr/bin/python3 /opt/Watcher3/watcher.py --port 2932

/opt/Watcher3/lib/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

Traceback (most recent call last):
  File "/opt/Watcher3/watcher.py", line 30, in <module>
    ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'
```

**Comment by nosmokingbandit** [comment]
Yeah, try to keep issues separate. It helps with my waning sanity.

Turns out that method was removed from the ssl module, then reinstated later on. Either way, this *should* be ok after commit 5f0bfcc04aaccccd458b757f6ecc15c1cf65b8f2. Let me know.

**Comment by OldMike** [comment]
Got another error. I'm sorry I dont code Python, I can't even help...

```mike@tv:/opt/Watcher3$ python3 watcher.py 
  File "watcher.py", line 36
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

**Comment by nosmokingbandit** [comment]
Completely remove the directory and re-clone. There are no exceptions formatted like that.

See lines 33/37
https://github.com/nosmokingbandit/Watcher3/blob/master/watcher.py

**Comment by OldMike** [comment]
Okay, I just pulled the first time. rm + git clone works like a charm. I'm gona test it!
