### ISSUE TITLE
No longer active?

### ISSUE THREAD

**Issue by barbequesauce** [nosmokingbandit/Watcher3#300]
Hi -

Love this tool, so much better than any alternative...

But the issues and PRs are starting to pile up. Is it no longer active?

@nosmokingbandit if you’re just too busy, maybe open up the contributor list so some others can help keep it alive? It’s clear that there is interest!

Thank you again for a great product!

**Comment by bartley69** [comment]
I really like this app, it has potential. It seems it is dead though...
