### ISSUE TITLE
Movies appear multiple times

### ISSUE THREAD

**Issue by j0hnsen** [nosmokingbandit/Watcher3#32]
I see that multiple movies appear 2-4 times in my watcher status page... Is this a known bug?

**Comment by nosmokingbandit** [comment]
I haven't seen that before. The database checks imdb numbers to keep duplicates out.

Did it just start happening with newly added movies, or have existing movies started duplicating themselves?

**Comment by j0hnsen** [comment]
Existing movies after the upgrade to the waiting status

**Comment by nosmokingbandit** [comment]
That's really weird... Do they show up twice if you go to `localhost:9090/manage#database` (or whatever your server is)?

The only change to the database for that update is changing movies to 'Waiting' when it is 'Wanted' but hasn't been found on predb, so I'm not sure what could have caused this. I'm wondering if it is actually doubled in the database or if the interface is rendering them twice.

If they show up twice in the database management page we'll check to see what the database holds.
