### ISSUE TITLE
Auto add and search trakt.tv list

### ISSUE THREAD

**Issue by PotatoQuality** [nosmokingbandit/Watcher3#38]
Will be very nice stuff if its possible to have a auto add function based on list from trakt.tv (like radarr has)

- Trending
- Popular
- Watched
- Collected
- Anticipated
- Box Office

Will be nice if you can config some settings likes: Need a higher score then 72 and not more results then 10 and how mutch time i will check again.

**Comment by nosmokingbandit** [comment]
I had looked at the Trakt api a while ago then completely forgot about it.

I'm working on a better interface on small screens, but once that is done I'll take a look at this.

**Comment by nosmokingbandit** [comment]
Added in commit https://github.com/nosmokingbandit/Watcher3/commit/f4fc41298f108f0b2f7c330144dd65431374a1e1

You can automatically add movies from any combination of those lists with a minimum score.

**Comment by PotatoQuality** [comment]
Is it possible to limited that I can config a year and the system will search after that year?

**Comment by PotatoQuality** [comment]
@nosmokingbandit i just enabled it, it doesn't look like it add a movie. i restarted it but it doesn't look like its working yet

**Comment by nosmokingbandit** [comment]
The first sync after restarting happens after a 25 minute delay (a lot of things happen when Watcher starts so I like to space things out to keep it smooth). How long have you waiting since startup?

**Comment by PotatoQuality** [comment]
@nosmokingbandit okay i will wait for 25 minuts. i will back for you :)

**Comment by PotatoQuality** [comment]
@nosmokingbandit i was wondering, will it log something when the add something from the list?

**Comment by PotatoQuality** [comment]
@nosmokingbandit nope, i don't see any movies added after 25 minuts :(

**Comment by nosmokingbandit** [comment]
The log should have entries that start with "core.trakt.get_list" every time it attempts to read a list. Do you have those?

**Comment by PotatoQuality** [comment]
@nosmokingbandit  hi, no, there not a single line with  core.trakt.get_list

**Comment by PotatoQuality** [comment]
Its look like the scheduler.TraktSync.create is not spawning

**Comment by Phault** [comment]
@PotatoQuality Are you looking at the log through Watcher's web interface? The dropdown for which log to view might be set to an older log by default (as mine is). 


Also there seems to be problem with the _popular_ list:
> KeyError: 'movie'
    return [i['movie'] for i in m if i['movie']['rating'] >= min_score]
  File "/watcher/core/trakt.py", line 86, in <listcomp>
    return [i['movie'] for i in m if i['movie']['rating'] >= min_score]
  File "/watcher/core/trakt.py", line 86, in get_list
Traceback (most recent call last):
ERROR 2017-05-06 17:30:42,445 core.trakt.get_list: Unable to get Trakt list
INFO 2017-05-06 17:30:42,263 core.trakt.get_list: Getting Trakt list popular

Apparently the trakt API is a bit inconsistent and the popular list only returns an array of movies and not an array of dictionaries with watcher count and the movie itself.

**Comment by nosmokingbandit** [comment]
I actually just fixed the popular list in https://github.com/nosmokingbandit/Watcher3/commit/c19f8da03f1164496959b8a87ff75c0b13a91592 (grumble grumble).

The only condition for the Trakt task to start is that the box is checked in settings, so I'm not sure what would keep it from starting. You are checking the box for Trakt *AND* the lists you want, right?

The log viewer in the web interface isn't great. Its ok for people to copy/paste a section right after something weird happens, but the actual text file is the only good way to read it.

**Comment by PotatoQuality** [comment]
I found out wat was going wrong. I check my fix over here and will be back soon

**Comment by PotatoQuality** [comment]
@nosmokingbandit it is working now! nice.

Thanks!
