### ISSUE TITLE
Mass search and auto snatch

### ISSUE THREAD

**Issue by j0hnsen** [nosmokingbandit/Watcher3#40]
Maybe I don't see this option but it would help me a lot if there would be an option where I could mark all snateched/wanted/found and force a search or auto snatch. I mean with around 20k of movies watcher is a bit slow so manual searches took more than 5 min per movie :(

**Comment by nosmokingbandit** [comment]
I don't have a massive library like that, so it is hard to know exactly where the bottlenecks are.

Would you mind sending me an email watchernab@gmail.com? I could use your help speeding things up, but it would be much easier to communicate via email.

**Comment by j0hnsen** [comment]
What is the status here?

**Comment by nosmokingbandit** [comment]
I'm finally back to going through my emails. The latest update was a bigger time sink than I expected. 

Added in 8459c8e2e13f8eab8462e605a8ff17249b93fdad.

In /library/manage you can force a backlog search on any selected movies.

**Comment by j0hnsen** [comment]
The whole manage page is as slow as hell with 20k Movies in the DB... Is there a way you could speed things up? I can't use it :/

**Comment by nosmokingbandit** [comment]
Objectively speaking the interface loads rather quickly. On identical hardware a similar application takes 4x as long to render 10 movies as Watcher does to render 500.

Iterating over 20k of anything is going to take time. What specific action causes the slowdown? Loading, selecting, etc?

**Comment by j0hnsen** [comment]
If I try to select my firefox and chrome keeps crashing... Sometimes it works after around 10-15 min. If I try to search for the movies again it sends a 500 internal server error.

**Comment by j0hnsen** [comment]
Ok latest update seems to bring a performance boost... But now I could force a backlog search of some movies and none get's into nzbget... Checked nzbget logs and watcher logs... There is no nzb downloaded from watcher but watcher found multiple releases.

**Comment by nosmokingbandit** [comment]
A backlog search doesn't grab releases, that will happen during the next scheduled event.
