### ISSUE TITLE
Can't start after upgrade

### ISSUE THREAD

**Issue by theflu** [nosmokingbandit/Watcher3#42]
Today I did a update from the GUI and now Watcher3 won't start

This is the error I am getting:
```
/opt/Watcher3# python3 /opt/Watcher3/watcher.py  --daemon
Traceback (most recent call last):
  File "/opt/Watcher3/watcher.py", line 22, in <module>
    from core import api, config, postprocessing, scheduler, sqldb
  File "/opt/Watcher3/core/api.py", line 6, in <module>
    from core import ajax, sqldb, poster
  File "/opt/Watcher3/core/ajax.py", line 9, in <module>
    from core import config, library, plugins, poster, searchresults, searcher, snatcher, sqldb, version
  File "/opt/Watcher3/core/config.py", line 6, in <module>
    from core import scheduler
  File "/opt/Watcher3/core/scheduler.py", line 8, in <module>
    from core import searcher, version
  File "/opt/Watcher3/core/searcher.py", line 5, in <module>
    from core import library, searchresults, snatcher, sqldb, proxy
  File "/opt/Watcher3/core/library.py", line 5, in <module>
    from core import sqldb, searchresults, searcher, snatcher, poster, plugins
  File "/opt/Watcher3/core/snatcher.py", line 5, in <module>
    from core import library, plugins, sqldb
ImportError: cannot import name 'library'
```

**Comment by nosmokingbandit** [comment]
Run `git pull` in the folder with Watcher and see if that resolves anything.

**Comment by theflu** [comment]
I tried that already, it said it was already up to date. I also did a fresh
clone and gave the same error when I tried to start it.

**Comment by theflu** [comment]
I pulled the latest this morning and the error has changed.
```
Traceback (most recent call last):
  File "watcher.py", line 22, in <module>
    from core import api, config, postprocessing, scheduler, sqldb
  File "/opt/Watcher3/core/api.py", line 5, in <module>
    from core import ajax, sqldb
  File "/opt/Watcher3/core/ajax.py", line 9, in <module>
    from core import config, library, plugins, searchresults, searcher, snatcher, sqldb, version
  File "/opt/Watcher3/core/config.py", line 6, in <module>
    from core import scheduler
  File "/opt/Watcher3/core/scheduler.py", line 9, in <module>
    from core.rss import imdb, popularmovies
  File "/opt/Watcher3/core/rss/imdb.py", line 2, in <module>
    from core import ajax, sqldb
ImportError: cannot import name 'ajax'
```

**Comment by theflu** [comment]
I reverted to a old commit to get it working
```
git checkout cc5b4fd5c3f27bf9ee65942ba261db2bb8aa8e4c
```

**Comment by nosmokingbandit** [comment]
I cloned a fresh copy on both Windows 10 and Debian and everything worked fine, so I'm not sure what the problem could be.

What OS are you running?

**Comment by theflu** [comment]
Ubuntu 14.04.5 LTS

**Comment by theflu** [comment]
I just did a fresh install of Ubuntu 14.04.5 LTS, updated it cloned watcher3 and it had the same error.

**Comment by bundyboss** [comment]
Bananian 16.04 r01 (it's like ubuntu) and for ARM

**Comment by nosmokingbandit** [comment]
I'm going to guess you are all using python 3.4 or thereabouts? It seems like there is a difference between 3.6 and 3.4 (and possibly other earlier versions) that affect how modules are imported.

I've fixed the problem, but while I was working on it I cleaned up a lot of code and streamlined some things, so I want to test everything again before I push the fix. I'll post here again to let you all know when the update is out.

**Comment by nosmokingbandit** [comment]
89a2de1695750dde39345f332385d7b73bd087eb made everything work for me using python 3.4 and 3.6 on windows 10. I'm not 100% sure how to run multiple versions of python3 on debian and I'm not energetic enough to play around on my server right now.

**Comment by bundyboss** [comment]
Hi, I can now start Watcher3 using the master branch but I can't add a movie:
  response.body = self.handler()
  File "/opt/Watcher3/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/Watcher3/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/Watcher3/core/ajax.py", line 103, in add_wanted_movie
    r = self.manage.add_movie(data, full_metadata=full_metadata)
  File "/opt/Watcher3/core/library.py", line 630, in add_movie
    tmdbid = data['id']

**Comment by theflu** [comment]
Everything is working fine for me thanks!

**Comment by nosmokingbandit** [comment]
Hey I'm really far behind on everything, but it looks like everything here is ok so I'm going to close this. If I'm wrong I'll open it up again.
