### ISSUE TITLE
some errors when Watcher looking for new available releases

### ISSUE THREAD

**Issue by toogaz** [nosmokingbandit/Watcher3#44]
WARNING:core.snatcher:Unable to automatically grab tt1856101, no results.
INFO:core.sqldb:Retrieving list of user's movies.
Myip - Myuser [11/May/2017:09:47:02] "GET /status/ HTTP/1.1" 200 20909                                                                                     "http://Mysite.ddns.us:9090/add_movie/" "Mozilla/5.0 (Windows NT 10.0; Win64; x6                                                                                    4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36"
Myip - Myuser [11/May/2017:09:47:02] "GET /static/images/posters/tt1856                                                                                    101.jpg HTTP/1.1" 200 16009 "http://Mysite.ddns.us:9090/status/" "Mozilla/5.0 (W                                                                                    indows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3                                                                                    029.96 Safari/537.36"
INFO:core.rss.predb:Checking predb.me for new available releases.
INFO:core.sqldb:Retrieving list of user's movies.
INFO:core.rss.predb:Checking predb.me for new available releases for A Dog's Pur                                                                                    pose.
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 1186, in run
    self.function(*self.args, **self.kwargs)
  File "/opt/Watcher3/core/cp_plugins/taskscheduler.py", line 122, in task
    self.func()
  File "/opt/Watcher3/core/searcher.py", line 58, in auto_search_and_grab
    self.predb.check_all()
  File "/opt/Watcher3/core/rss/predb.py", line 33, in check_all
    self.check_one(movie)
  File "/opt/Watcher3/core/rss/predb.py", line 61, in check_one
    if self.fuzzy_match(rss_titles, test):
  File "/opt/Watcher3/core/rss/predb.py", line 118, in fuzzy_match
    match = fuzz.partial_ratio(item, test)
  File "/opt/Watcher3/lib/fuzzywuzzy/utils.py", line 23, in decorator
    return func(*args, **kwargs)
  File "/opt/Watcher3/lib/fuzzywuzzy/utils.py", line 32, in decorator
    return func(*args, **kwargs)
  File "/opt/Watcher3/lib/fuzzywuzzy/fuzz.py", line 69, in partial_ratio
    blocks = m.get_matching_blocks()
  File "/opt/Watcher3/lib/fuzzywuzzy/StringMatcher.py", line 59, in get_matching                                                                                    _blocks
    self._str1, self._str2)
TypeError: inverse expected a list of edit operations

**Comment by toogaz** [comment]
I think this errors arrived with the specials caracters (éèà etc...)
Adding infos

 Logs Watcher3
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  Content-Length: 61
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.96 Safari/537.36
  ORIGIN: http://Mysite.ddns.us:9090
  ACCEPT-ENCODING: gzip, deflate
  CONNECTION: keep-alive
  HOST: Mysite.ddns.us:9090
  COOKIE: list_style=posters; stay_login=0; session_id=538bd504cda30701d28280b7fc3ae3e060d5ee7b
  X-REQUESTED-WITH: XMLHttpRequest
  Remote-Addr: 37.58.170.250
  ACCEPT-LANGUAGE: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
  REFERER: http://Mysite.ddns.us:9090/
  ACCEPT: */*
Request Headers:
INFO 2017-05-11 13:33:48,717 cherrypy.error.1969160112.error: [11/May/2017:13:33:48] HTTP 
INFO 2017-05-11 13:33:48,701 core.sqldb.get_search_results: Retrieving Search Results for tt2304933.
INFO 2017-05-11 13:33:48,396 root.search_newznab: SEARCHING: http://Mysearch.gouv/api?apikey=APIKEY&t=movie&imdbid=2304933
INFO 2017-05-11 13:33:41,574 core.sqldb.get_search_results: Retrieving Search Results for tt2304933.
INFO 2017-05-11 13:33:41,558 core.sqldb.get_movie_details: Retrieving details for tt2304933.
INFO 2017-05-11 13:33:33,380 core.sqldb.get_user_movies: Retrieving list of user's movies.
INFO 2017-05-11 13:32:59,459 core.sqldb.get_user_movies: Retrieving list of user's movies.


the rss result 

<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:newznab="http://www.newznab.com/DTD/2010/feeds/attributes/" version="2.0">
<channel>
<atom:link href="http://Mysearch.gouv/api?apikey=APIKEY&t=movie&imdbid=2304933" rel="self" type="application/rss+xml"/>
<title>My Search Gouv</title>
<description>My Search Gouv Feed</description>
<link>http://Mysearch.gouv/</link>
<language>fr-fr</language>
<webMaster>admin@Mysearch.gouv (My Search Gouv)</webMaster>
<category/>
<image>
<url>
http://Mysearch.gouv/templates/default/images/banner.jpg
</url>
<title>My Search Gouv</title>
<link>http://Mysearch.gouv/</link>
<description>
Visit My Search Gouv - My Search Gouv - référencement de Newsgroups
</description>
</image>
<newznab:response offset="0" total="12"/>
<item>
<title>The.Wave.2016 French Xvid.FRENCH.SDTV.BR-RIP</title>
<guid isPermaLink="true">
http://Mysearch.gouv/details/6714400228bbcec9437fa4fa147fff03
</guid>
<link>
http://Mysearch.gouv/getnzb/6714400228bbcec9437fa4fa147fff03.nzb&i=24&r=24f6342707bccb7584076a869eb528ed
</link>
<comments>
http://Mysearch.gouv/details/6714400228bbcec9437fa4fa147fff03#comments
</comments>
<pubDate>Wed, 26 Apr 2017 20:14:10 +0200</pubDate>
<category>Films > SD</category>
<description>The.Wave.2016 French Xvid</description>
<enclosure url="http://Mysearch.gouv/getnzb/6714400228bbcec9437fa4fa147fff03.nzb&i=24&r=24f6342707bccb7584076a869eb528ed" length="1299856061" type="application/x-nzb"/>
<newznab:attr name="category" value="2000"/>
<newznab:attr name="category" value="2030"/>
<newznab:attr name="size" value="1299856061"/>
<newznab:attr name="guid" value="6714400228bbcec9437fa4fa147fff03"/>
</item>
<item>
<title>La 5ème Vague (2016).FRENCH.720p.bluray.X264.mkv</title>
<guid isPermaLink="true">
http://Mysearch.gouv/details/3d48c90eef45c34e3949bf42b378ed81
</guid>
<link>
http://Mysearch.gouv/getnzb/3d48c90eef45c34e3949bf42b378ed81.nzb&i=24&r=24f6342707bccb7584076a869eb528ed
</link>
<comments>
http://Mysearch.gouv/details/3d48c90eef45c34e3949bf42b378ed81#comments
</comments>
<pubDate>Tue, 05 Jul 2016 00:05:31 +0200</pubDate>
<category>Films > HD</category>
<description>La 5ème Vague (2016)</description>
<enclosure url="http://Mysearch.gouv/getnzb/3d48c90eef45c34e3949bf42b378ed81.nzb&i=24&r=24f6342707bccb7584076a869eb528ed" length="843077886" type="application/x-nzb"/>
<newznab:attr name="category" value="2000"/>
<newznab:attr name="category" value="2040"/>
<newznab:attr name="size" value="843077886"/>
<newznab:attr name="guid" value="3d48c90eef45c34e3949bf42b378ed81"/>
</item>
<item>
<title>La 5ème vague (2016).FRENCH.1080p.bluray.X264.mkv</title>
<guid isPermaLink="true">
http://Mysearch.gouv/details/6a62c305698fb3e3786c4ae2d28b7618
</guid>
<link>
http://Mysearch.gouv/getnzb/6a62c305698fb3e3786c4ae2d28b7618.nzb&i=24&r=24f6342707bccb7584076a869eb528ed
</link>
<comments>
http://Mysearch.gouv/details/6a62c305698fb3e3786c4ae2d28b7618#comments
</comments>
<pubDate>Sun, 03 Jul 2016 12:27:54 +0200</pubDate>
<category>Films > HD</category>
<description>La 5ème vague (2016)</description>
<enclosure url="http://Mysearch.gouv/getnzb/6a62c305698fb3e3786c4ae2d28b7618.nzb&i=24&r=24f6342707bccb7584076a869eb528ed" length="10782660325" type="application/x-nzb"/>
<newznab:attr name="category" value="2000"/>
<newznab:attr name="category" value="2040"/>
<newznab:attr name="size" value="10782660325"/>
<newznab:attr name="guid" value="6a62c305698fb3e3786c4ae2d28b7618"/>
</item>
<item>
<title>La 5ème vague (2016).FRENCH.720p.bluray.X264.mkv</title>
<guid isPermaLink="true">
http://Mysearch.gouv/details/084d3d51a24ba62eed1b34c7fcb31a9e
</guid>
<link>
http://Mysearch.gouv/getnzb/084d3d51a24ba62eed1b34c7fcb31a9e.nzb&i=24&r=24f6342707bccb7584076a869eb528ed
</link>
<comments>
http://Mysearch.gouv/details/084d3d51a24ba62eed1b34c7fcb31a9e#comments
</comments>
<pubDate>Fri, 01 Jul 2016 15:10:26 +0200</pubDate>
<category>Films > HD</category>
<description>La 5ème vague (2016)</description>
<enclosure url="http://Mysearch.gouv/getnzb/084d3d51a24ba62eed1b34c7fcb31a9e.nzb&i=24&r=24f6342707bccb7584076a869eb528ed" length="5393679897" type="application/x-nzb"/>
<newznab:attr name="category" value="2000"/>
<newznab:attr name="category" value="2040"/>
<newznab:attr name="size" value="5393679897"/>
<newznab:attr name="guid" value="084d3d51a24ba62eed1b34c7fcb31a9e"/>
</item>
<item>
<title>La 5ème vague (2016).FRENCH.SDTV.BR-RIP</title>
<guid isPermaLink="true">
http://Mysearch.gouv/details/3c6480944a89d8559ce1275f89798d30
</guid>
<link>
http://Mysearch.gouv/getnzb/3c6480944a89d8559ce1275f89798d30.nzb&i=24&r=24f6342707bccb7584076a869eb528ed
</link>
<comments>
http://Mysearch.gouv/details/3c6480944a89d8559ce1275f89798d30#comments
</comments>
<pubDate>Fri, 01 Jul 2016 15:10:35 +0200</pubDate>
<category>Films > SD</category>
<description>La 5ème vague (2016)</description>
<enclosure url="http://Mysearch.gouv/getnzb/3c6480944a89d8559ce1275f89798d30.nzb&i=24&r=24f6342707bccb7584076a869eb528ed" length="845823172" type="application/x-nzb"/>
<newznab:attr name="category" value="2000"/>
<newznab:attr name="category" value="2030"/>
<newznab:attr name="size" value="845823172"/>
<newznab:attr name="guid" value="3c6480944a89d8559ce1275f89798d30"/>
</item>
<item>
<title>La 5ème vague (2016).FRENCH.SDTV.BR-RIP</title>
<guid isPermaLink="true">
http://Mysearch.gouv/details/9c0dc3becdda82e52a9d7d2a69b56c8b
</guid>
<link>
http://Mysearch.gouv/getnzb/9c0dc3becdda82e52a9d7d2a69b56c8b.nzb&i=24&r=24f6342707bccb7584076a869eb528ed
</link>
<comments>
http://Mysearch.gouv/details/9c0dc3becdda82e52a9d7d2a69b56c8b#comments
</comments>
<pubDate>Sun, 05 Jun 2016 10:33:23 +0200</pubDate>
<category>Films > SD</category>
<description>La 5ème vague (2016)</description>
<enclosure url="http://Mysearch.gouv/getnzb/9c0dc3becdda82e52a9d7d2a69b56c8b.nzb&i=24&r=24f6342707bccb7584076a869eb528ed" length="856615216" type="application/x-nzb"/>
<newznab:attr name="category" value="2000"/>
<newznab:attr name="category" value="2030"/>
<newznab:attr name="size" value="856615216"/>
<newznab:attr name="guid" value="9c0dc3becdda82e52a9d7d2a69b56c8b"/>
</item>
<item>
<title>La 5ème vague (2016).FRENCH.SDTV.BR-RIP</title>
<guid isPermaLink="true">
http://Mysearch.gouv/details/a8ca5c773489b36e228ebd1be273bc61
</guid>
<link>
http://Mysearch.gouv/getnzb/a8ca5c773489b36e228ebd1be273bc61.nzb&i=24&r=24f6342707bccb7584076a869eb528ed
</link>
<comments>
http://Mysearch.gouv/details/a8ca5c773489b36e228ebd1be273bc61#comments
</comments>
<pubDate>Sat, 04 Jun 2016 04:23:04 +0200</pubDate>
<category>Films > SD</category>
<description>La 5ème vague (2016)</description>
<enclosure url="http://Mysearch.gouv/getnzb/a8ca5c773489b36e228ebd1be273bc61.nzb&i=24&r=24f6342707bccb7584076a869eb528ed" length="907124499" type="application/x-nzb"/>
<newznab:attr name="category" value="2000"/>
<newznab:attr name="category" value="2030"/>
<newznab:attr name="size" value="907124499"/>
<newznab:attr name="guid" value="a8ca5c773489b36e228ebd1be273bc61"/>
</item>
<item>
<title>La 5ème vague (2016).FRENCH.1080p.bluray.X264.mkv</title>
<guid isPermaLink="true">
http://Mysearch.gouv/details/d014af2993a416e81e318d0bed33295d
</guid>
<link>
http://Mysearch.gouv/getnzb/d014af2993a416e81e318d0bed33295d.nzb&i=24&r=24f6342707bccb7584076a869eb528ed
</link>
<comments>
http://Mysearch.gouv/details/d014af2993a416e81e318d0bed33295d#comments
</comments>
<pubDate>Wed, 04 May 2016 12:23:12 +0200</pubDate>
<category>Films > HD</category>
<description>La 5ème vague (2016)</description>
<enclosure url="http://Mysearch.gouv/getnzb/d014af2993a416e81e318d0bed33295d.nzb&i=24&r=24f6342707bccb7584076a869eb528ed" length="10777056021" type="application/x-nzb"/>
<newznab:attr name="category" value="2000"/>
<newznab:attr name="category" value="2040"/>
<newznab:attr name="size" value="10777056021"/>
<newznab:attr name="guid" value="d014af2993a416e81e318d0bed33295d"/>
</item>
<item>
<title>La 5ème vague (2016).FRENCH.720p.bluray.X264.mkv</title>
<guid isPermaLink="true">
http://Mysearch.gouv/details/782405e964e5dff627d7a5616237a4f8
</guid>
<link>
http://Mysearch.gouv/getnzb/782405e964e5dff627d7a5616237a4f8.nzb&i=24&r=24f6342707bccb7584076a869eb528ed
</link>
<comments>
http://Mysearch.gouv/details/782405e964e5dff627d7a5616237a4f8#comments
</comments>
<pubDate>Wed, 04 May 2016 13:55:33 +0200</pubDate>
<category>Films > HD</category>
<description>La 5ème vague (2016)</description>
<enclosure url="http://Mysearch.gouv/getnzb/782405e964e5dff627d7a5616237a4f8.nzb&i=24&r=24f6342707bccb7584076a869eb528ed" length="5328347579" type="application/x-nzb"/>
<newznab:attr name="category" value="2000"/>
<newznab:attr name="category" value="2040"/>
<newznab:attr name="size" value="5328347579"/>
<newznab:attr name="guid" value="782405e964e5dff627d7a5616237a4f8"/>
</item>
<item>
<guid isPermaLink="true">
http://Mysearch.gouv/details/fe256c6f7e4f27811c1fd093a709bbaf
</guid>
<link>
http://Mysearch.gouv/getnzb/fe256c6f7e4f27811c1fd093a709bbaf.nzb&i=24&r=24f6342707bccb7584076a869eb528ed
</link>
<comments>
http://Mysearch.gouv/details/fe256c6f7e4f27811c1fd093a709bbaf#comments
</comments>
<pubDate>Tue, 12 Apr 2016 18:11:23 +0200</pubDate>
<category>Films > Other</category>
<description>La 5ème vague (2016)</description>
<enclosure url="http://Mysearch.gouv/getnzb/fe256c6f7e4f27811c1fd093a709bbaf.nzb&i=24&r=24f6342707bccb7584076a869eb528ed" length="156750802" type="application/x-nzb"/>
<newznab:attr name="category" value="2000"/>
<newznab:attr name="category" value="2020"/>
<newznab:attr name="size" value="156750802"/>
<newznab:attr name="guid" value="fe256c6f7e4f27811c1fd093a709bbaf"/>
</item>
<item>
<guid isPermaLink="true">
http://Mysearch.gouv/details/4d8d837d588c20a061cca97f747fcca5
</guid>
<link>
http://Mysearch.gouv/getnzb/4d8d837d588c20a061cca97f747fcca5.nzb&i=24&r=24f6342707bccb7584076a869eb528ed
</link>
<comments>
http://Mysearch.gouv/details/4d8d837d588c20a061cca97f747fcca5#comments
</comments>
<pubDate>Fri, 08 Apr 2016 18:57:39 +0200</pubDate>
<category>Films > Other</category>
<description>La 5ème vague (2016)</description>
<enclosure url="http://Mysearch.gouv/getnzb/4d8d837d588c20a061cca97f747fcca5.nzb&i=24&r=24f6342707bccb7584076a869eb528ed" length="9906989706" type="application/x-nzb"/>
<newznab:attr name="category" value="2000"/>
<newznab:attr name="category" value="2020"/>
<newznab:attr name="size" value="9906989706"/>
<newznab:attr name="guid" value="4d8d837d588c20a061cca97f747fcca5"/>
</item>
<item>
<guid isPermaLink="true">
http://Mysearch.gouv/details/364ff00dda8e208a9c50476e3119aa28
</guid>
<link>
http://Mysearch.gouv/getnzb/364ff00dda8e208a9c50476e3119aa28.nzb&i=24&r=24f6342707bccb7584076a869eb528ed
</link>
<comments>
http://Mysearch.gouv/details/364ff00dda8e208a9c50476e3119aa28#comments
</comments>
<pubDate>Tue, 05 Apr 2016 14:56:26 +0200</pubDate>
<category>Films > Other</category>
<description>La 5ème vague (2016)</description>
<enclosure url="http://Mysearch.gouv/getnzb/364ff00dda8e208a9c50476e3119aa28.nzb&i=24&r=24f6342707bccb7584076a869eb528ed" length="3467032467" type="application/x-nzb"/>
<newznab:attr name="category" value="2000"/>
<newznab:attr name="category" value="2020"/>
<newznab:attr name="size" value="3467032467"/>
<newznab:attr name="guid" value="364ff00dda8e208a9c50476e3119aa28"/>
</item>
</channel>
</rss>

**Comment by nosmokingbandit** [comment]
I just ran a few French movies (with all the typical accented characters) and wasn't able to reproduce this.

Can you send me the entire log so I can trace every step?

watchernzb@gmail.com

**Comment by nosmokingbandit** [comment]
442e5953a9c697cf343a9eaa02f0b89f62c1a967

Should fix this, let me know.
