### ISSUE TITLE
"Quick-Add" throws TypeError

### ISSUE THREAD

**Issue by tmajni** [nosmokingbandit/Watcher3#46]
INFO 2017-05-14 00:56:25,389 cherrypy.error.140452261263568.error: [14/May/2017:00:56:25] HTTP 
TypeError: string indices must be integers
    tmdbid = data['id']
  File "/opt/Watcher3/core/library.py", line 630, in add_movie
    r = self.manage.add_movie(data, full_metadata=full_metadata)
  File "/opt/Watcher3/core/ajax.py", line 103, in add_wanted_movie
    return self.callable(*self.args, **self.kwargs)
  File "/opt/Watcher3/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/Watcher3/lib/cherrypy/lib/encoding.py", line 220, in __call__
    response.body = self.handler()
  File "/opt/Watcher3/lib/cherrypy/_cprequest.py", line 670, in respond
Traceback (most recent call last):
ERROR 2017-05-14 00:56:25,385 cherrypy.error.140452261263568.error: [14/May/2017:00:56:25] HTTP 
INFO 2017-05-14 00:56:21,149 core.movieinfo._search_title: Searching TMDB https://api.themoviedb.org/3/search/movie?

**Comment by tmajni** [comment]
closed without comment?  

Putting my feet back up on the couch, as in CouchPotato!!!!!!!!!!!

**Comment by PotatoQuality** [comment]
Read the reason line why its closed..... 


" nosmokingbandit closed this in 90f11e2 2 days ago "

Hint: he Fixed the error

**Comment by nosmokingbandit** [comment]
Sometimes Git closes issues automatically when the word "fix" is close to an issue reference. But not all the time. I haven't figured out *exactly* what triggers it. I'd like to turn it off but I don't think that is possible.
