### ISSUE TITLE
Movie does not change status to finished after completion

### ISSUE THREAD

**Issue by andrewdens** [nosmokingbandit/Watcher3#47]
Downloaded movies remain as Snatched, no updates after the movie has finished downloading. I've checked watcher logs and did not find any other changes after the following:
`
INFO 2017-05-19 17:09:05,324 core.sqldb.update: Updating status to Snatched for col <movie> in MOVIES.
INFO 2017-05-19 17:09:05,324 core.library.movie_status: Setting MOVIES <movie> status to Snatched.
`
I checked recent Sabnzbd logs as well but could not find any error messages related to the download.

Sabnzbd version: 	2.0.0 [55c4bef]

**Comment by nosmokingbandit** [comment]
Did you set up Sab according to the [wiki[(https://github.com/nosmokingbandit/Watcher3/wiki/Post-Processing) ?

If Sab is telling Watcher the download is done your Watcher log will have a section that looks like this:

    #################################
    Post-processing request received.
    #################################

**Comment by andrewdens** [comment]
Oh I didn't see that originally in installation steps. So far i've edited my /post scripts/sabnzbd.py conf as shown. However for the next step I do not see an option for selecting "watcher.py" as my script in Sabnzbd Categories menu. After just editing the conf section I tried again to no avail.

**Comment by andrewdens** [comment]
So far i've tried to follow the directions provided in these sabnzbd docs [https://sabnzbd.org/wiki/scripts/notification-scripts](url). I pointed the scripts folder to my copy of Sabnzbd.py after modifying the conf. Let's see if it works now

**Comment by nosmokingbandit** [comment]
Cool beans, thanks for closing the issue.
