### ISSUE TITLE
Manual Import - Post Download

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#49]
Request to add option to scan the downloads directory for occasions where post processing has failed.

**Comment by nosmokingbandit** [comment]
I'm thinking about a good way to do this. I'm sure I'll add this feature eventually, but I'll have to think about  how to make it efficient enough.

**Comment by nosmokingbandit** [comment]
Was added in 18fba910af2262a631b03040f72ea1e6bf547546, you can manually fire the scanner in settings/server
