### ISSUE TITLE
DTS being flagged as TS

### ISSUE THREAD

**Issue by theflu** [nosmokingbandit/Watcher3#51]
If a release name has DTS in it will get flagged as having TS in it.

**Comment by war59312** [comment]
Indeed. regex are tricky.

Issue appears to be @ https://github.com/nosmokingbandit/Watcher3/blob/196a6741f603ea84a948ba0f75ffb73bfdc2fcb2/lib/PTN/patterns.py#L9

**Comment by nosmokingbandit** [comment]
How is this happening? From search or import?

**Comment by theflu** [comment]
Search

**Comment by nosmokingbandit** [comment]
I've been playing around with the parser for a while, trying every combination I can think of, and I can't get it to report back incorrectly.

I prefer not to post release names publicly -- can you email me a name that is being parsed incorrectly? `watchernzb@gmail.com`

**Comment by nosmokingbandit** [comment]
Closing due to age. If this still needs attention feel free to post again.
