### ISSUE TITLE
[Feature Request] Update Plex Library after Post-Processing

### ISSUE THREAD

**Issue by mikepruett3** [nosmokingbandit/Watcher3#52]
I'll be the first to admit, I really don't know my way with Python. I was hoping that there would be a way to (maybe with a plugin) to make an API call to a Plex Server after Post-Processing has finished... to have it update the Movies Library. (Instead of having to schedule an Library update every few hours)

I have tried adding my "best-effort" to the end of the sabnzbd.py post-processing script... but it failed miserably after moving to Python3.

Definitely not the highest priority, but it would be nice to see down the road. Keep up the great work, this project is amazing!

**Comment by PotatoQuality** [comment]
+1

**Comment by jaketame** [comment]
I've been trying to think on how to do this and there seems to be three situations

1) Watcher + Plex are local so you can run plex scanner for specific movie file
2) Watcher is in Docker or Plex is in Docker - You can't run plex scanner, have to refresh entire movie library
3) Both are on different machines - You can't run plex scanner, have to refresh entire movie library

**Comment by theflu** [comment]
There is a option in plex for it to watch for changes in your media directories and will update when a change it detected.

**Comment by jaketame** [comment]
I've created a pull request on watcher plugins for plex_scan via api.

https://github.com/nosmokingbandit/watcherplugins

**Comment by nosmokingbandit** [comment]
I merged your request, so I'm closing this. Thanks for helping the community, we all appreciate it.
