### ISSUE TITLE
The PirateBay provider is searching using imdbid

### ISSUE THREAD

**Issue by tproenca** [nosmokingbandit/Watcher3#53]
The search procedure uses imdbid on piratebay to search. That reduces the number of matches significantly since a lot of torrents don't include imdbid. 
I would suggest to perform a movie name search like couchpotato does.

**Comment by nosmokingbandit** [comment]
Couchpotato often downloads incorrect movies, so I'm not eager to emulate it. Any release group worth their salt is going to include the imdbid in the metadata. I have no intention to change this.
