### ISSUE TITLE
[feature request] show from where its added

### ISSUE THREAD

**Issue by PotatoQuality** [nosmokingbandit/Watcher3#55]
It will be nice if we show how the movie is added.

Status can be:  API, added manual, Automatic added from list  or automatic added from trakt.tv

**Comment by nosmokingbandit** [comment]
Added in commit 8956d82ed309fa0daa55e6d75ed5f58798a32455. Will only show sources for movies added in the future.

**Comment by PotatoQuality** [comment]
Nice! Thanks @nosmokingbandit  :D
