### ISSUE TITLE
New Version require Python 3

### ISSUE THREAD

**Issue by fire90** [nosmokingbandit/Watcher3#56]
Hello,
old version on my Qnap worked great but on new one i can't start it because python 3 is required, i install python but still same message. 

thank's for your help.

**Comment by nosmokingbandit** [comment]
I don't know much about the qnap OS, but I'd make sure you have [this package[(https://www.qnap.com/en-uk/app_center/con_show.php?op=showone&internalName=Python3&version=3.5.0.2&down_1_name=TS-NASX86&jump_win=1&qts=4.2.2&seq=46) installed, then make sure you are launching watcher with `python3 watcher.py`.
