### ISSUE TITLE
Login page theming is broken after the transition to Mako

### ISSUE THREAD

**Issue by Phault** [nosmokingbandit/Watcher3#57]
The login template is still looking for "${url_base}/auth/static/css/themes/theme.css?v=06.02", while instead it should be using the appropriate css for the active theme.

**Comment by nosmokingbandit** [comment]
Fixed in commit 841ca937c8800567022e71bae385a916ca01a929

The only page I forgot to test after setting up theme options. It should have still worked, right? Just really ugly.

**Comment by Phault** [comment]
Heh I figured it was just an oversight. But yes it still worked :)
