### ISSUE TITLE
New update breaks functionality

### ISSUE THREAD

**Issue by WilliamJBrown** [nosmokingbandit/Watcher3#58]
Just tried updating and nothing I am trying is letting me able use the new update. Am using the [docker version](https://hub.docker.com/r/williambroown/watcherdocker/) so not sure if something is needed that is dependant on it to operate the new version. Tried installing from fresh and just getting 404 not founds. 

Cleared out the database as was throwing an error at first. 

Cannot save settings. Search movies, import movies. 

Not sure what is going on right now. Cant seem to make sense of log files either as they seem to be missing information? 

`INFO 2017-06-08 22:28:54,175 __main__.<module>: SQL DB not found. Creating.
DEBUG 2017-06-08 22:28:54,175 core.sqldb.create_database: Creating tables.
INFO 2017-06-08 22:28:54,190 core.version.update_check: Checking git for a new version.
INFO 2017-06-08 22:28:54,562 core.version.update_check: Current local hash: 48b4ea447c45b1909bcab64a081bc9866397aa27
INFO 2017-06-08 22:28:54,568 cherrypy.error.error: [08/Jun/2017:22:28:54] ENGINE Listening for SIGUSR1.
INFO 2017-06-08 22:28:54,568 cherrypy.error.error: [08/Jun/2017:22:28:54] ENGINE Listening for SIGTERM.
INFO 2017-06-08 22:28:54,568 cherrypy.error.error: [08/Jun/2017:22:28:54] ENGINE Listening for SIGHUP.
INFO 2017-06-08 22:28:54,568 cherrypy.error.error: [08/Jun/2017:22:28:54] ENGINE Bus STARTING
INFO 2017-06-08 22:28:54,687 cherrypy.error.error: [08/Jun/2017:22:28:54] ENGINE Serving on http://0.0.0.0:9090
INFO 2017-06-08 22:28:54,688 cherrypy.error.error: [08/Jun/2017:22:28:54] ENGINE Bus STARTED
DEBUG 2017-06-08 22:29:13,488 core.sqldb.get_user_movies: Retrieving list of user's movies.
INFO 2017-06-08 22:29:54,693 core.version.update_check: Checking git for a new version.
INFO 2017-06-08 22:29:55,015 core.version.update_check: Current local hash: 48b4ea447c45b1909bcab64a081bc9866397aa27
DEBUG 2017-06-08 22:30:45,627 core.sqldb.get_user_movies: Retrieving list of user's movies.
INFO 2017-06-08 22:41:39,825 cherrypy.error.error: [08/Jun/2017:22:41:39] ENGINE Caught signal SIGTERM.
INFO 2017-06-08 22:41:39,825 cherrypy.error.error: [08/Jun/2017:22:41:39] ENGINE Bus STOPPING
INFO 2017-06-08 22:41:39,826 cherrypy.error.error: [08/Jun/2017:22:41:39] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9090)) shut down
INFO 2017-06-08 22:41:39,827 core.cp_plugins.taskscheduler.stop: Stopping scheduled task update_check.
INFO 2017-06-08 22:41:39,827 core.cp_plugins.taskscheduler.stop: Stopping scheduled task imdb_sync.
INFO 2017-06-08 22:41:39,827 core.cp_plugins.taskscheduler.stop: Stopping scheduled task popularmovies_sync.
INFO 2017-06-08 22:41:39,827 core.cp_plugins.taskscheduler.stop: Stopping scheduled task search_all.
INFO 2017-06-08 22:41:39,827 core.cp_plugins.taskscheduler.stop: Stopping scheduled task trakt_sync.
INFO 2017-06-08 22:41:39,827 cherrypy.error.error: [08/Jun/2017:22:41:39] ENGINE Bus STOPPED
INFO 2017-06-08 22:41:39,827 cherrypy.error.error: [08/Jun/2017:22:41:39] ENGINE Bus EXITING
INFO 2017-06-08 22:41:39,827 cherrypy.error.error: [08/Jun/2017:22:41:39] ENGINE Bus EXITED
INFO 2017-06-08 22:41:39,827 cherrypy.error.error: [08/Jun/2017:22:41:39] ENGINE Waiting for child threads to terminate...
INFO 2017-06-08 22:42:05,764 __main__.<module>: SQL DB not found. Creating.
DEBUG 2017-06-08 22:42:05,764 core.sqldb.create_database: Creating tables.
INFO 2017-06-08 22:42:05,771 core.version.update_check: Checking git for a new version.
INFO 2017-06-08 22:42:06,127 core.version.update_check: Current local hash: 48b4ea447c45b1909bcab64a081bc9866397aa27
INFO 2017-06-08 22:42:06,133 cherrypy.error.error: [08/Jun/2017:22:42:06] ENGINE Listening for SIGTERM.
INFO 2017-06-08 22:42:06,134 cherrypy.error.error: [08/Jun/2017:22:42:06] ENGINE Listening for SIGHUP.
INFO 2017-06-08 22:42:06,134 cherrypy.error.error: [08/Jun/2017:22:42:06] ENGINE Listening for SIGUSR1.
INFO 2017-06-08 22:42:06,134 cherrypy.error.error: [08/Jun/2017:22:42:06] ENGINE Bus STARTING
INFO 2017-06-08 22:42:06,241 cherrypy.error.error: [08/Jun/2017:22:42:06] ENGINE Serving on http://0.0.0.0:9090
INFO 2017-06-08 22:42:06,242 cherrypy.error.error: [08/Jun/2017:22:42:06] ENGINE Bus STARTED
DEBUG 2017-06-08 22:42:14,274 core.sqldb.get_user_movies: Retrieving list of user's movies.
DEBUG 2017-06-08 22:42:23,770 core.sqldb.get_user_movies: Retrieving list of user's movies.
INFO 2017-06-08 22:46:50,623 cherrypy.error.error: [08/Jun/2017:22:46:50] ENGINE Caught signal SIGTERM.
INFO 2017-06-08 22:46:50,624 cherrypy.error.error: [08/Jun/2017:22:46:50] ENGINE Bus STOPPING
INFO 2017-06-08 22:46:50,624 cherrypy.error.error: [08/Jun/2017:22:46:50] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9090)) shut down
INFO 2017-06-08 22:46:50,625 core.cp_plugins.taskscheduler.stop: Stopping scheduled task search_all.
INFO 2017-06-08 22:46:50,625 core.cp_plugins.taskscheduler.stop: Stopping scheduled task imdb_sync.
INFO 2017-06-08 22:46:50,625 core.cp_plugins.taskscheduler.stop: Stopping scheduled task update_check.
INFO 2017-06-08 22:46:50,625 core.cp_plugins.taskscheduler.stop: Stopping scheduled task popularmovies_sync.
INFO 2017-06-08 22:46:50,625 core.cp_plugins.taskscheduler.stop: Stopping scheduled task trakt_sync.
INFO 2017-06-08 22:46:50,625 cherrypy.error.error: [08/Jun/2017:22:46:50] ENGINE Bus STOPPED
INFO 2017-06-08 22:46:50,625 cherrypy.error.error: [08/Jun/2017:22:46:50] ENGINE Bus EXITING
INFO 2017-06-08 22:46:50,625 cherrypy.error.error: [08/Jun/2017:22:46:50] ENGINE Bus EXITED
INFO 2017-06-08 22:46:50,643 cherrypy.error.error: [08/Jun/2017:22:46:50] ENGINE Waiting for child threads to terminate...
INFO 2017-06-08 22:47:11,641 __main__.<module>: SQL DB not found. Creating.
DEBUG 2017-06-08 22:47:11,641 core.sqldb.create_database: Creating tables.
INFO 2017-06-08 22:47:11,649 core.version.update_check: Checking git for a new version.
INFO 2017-06-08 22:47:11,975 core.version.update_check: Current local hash: 48b4ea447c45b1909bcab64a081bc9866397aa27
INFO 2017-06-08 22:47:11,981 cherrypy.error.error: [08/Jun/2017:22:47:11] ENGINE Listening for SIGUSR1.
INFO 2017-06-08 22:47:11,982 cherrypy.error.error: [08/Jun/2017:22:47:11] ENGINE Listening for SIGHUP.
INFO 2017-06-08 22:47:11,982 cherrypy.error.error: [08/Jun/2017:22:47:11] ENGINE Listening for SIGTERM.
INFO 2017-06-08 22:47:11,982 cherrypy.error.error: [08/Jun/2017:22:47:11] ENGINE Bus STARTING
INFO 2017-06-08 22:47:12,090 cherrypy.error.error: [08/Jun/2017:22:47:12] ENGINE Serving on http://0.0.0.0:9090
INFO 2017-06-08 22:47:12,091 cherrypy.error.error: [08/Jun/2017:22:47:12] ENGINE Bus STARTED`

Let me know what I can do to troubleshoot or get more information for you :)

**Comment by nosmokingbandit** [comment]
There was a bungled update, everything should be normal again with a `git pull` or rebuilding the container since it will clone the latest commit.

I'm an idiot when it comes to git and sometimes it doesn't do what I think it should and things get weird.

**Comment by WilliamJBrown** [comment]
Just fully updated the container to the current update. It seems like it has troubles creating the database. What ever setting I do seems to not able to create the database in the specified folder. 

`TypeError: {'error', 'Unable to read database'} is not JSON serializable
    raise TypeError(repr(o) + " is not JSON serializable")
  File "/usr/lib64/python3.5/json/encoder.py", line 179, in default
    return _iterencode(o, 0)
  File "/usr/lib64/python3.5/json/encoder.py", line 256, in iterencode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.5/json/encoder.py", line 198, in encode
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.5/json/__init__.py", line 230, in dumps
    return json.dumps(self.manage.get_stats())
  File "/opt/watcher3/app/core/ajax.py", line 1169, in generate_stats
    return self.callable(*self.args, **self.kwargs)
  File "/opt/watcher3/app/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/opt/watcher3/app/lib/cherrypy/lib/encoding.py", line 220, in __call__
    response.body = self.handler()
  File "/opt/watcher3/app/lib/cherrypy/_cprequest.py", line 670, in respond
Traceback (most recent call last):`

**Comment by nosmokingbandit** [comment]
64abbb718875ae11a4582ebaf89d0d335e7657cf should take care of it. You shouldn't need to do anything except update Watcher.

I did some pretty hacky things early on that I'm slowly fixing, but that only uncovers other problems I should have fixed early on.

**Comment by WilliamJBrown** [comment]
Works great thank you! Looks pretty too. Worth all the work :D 👍
