### ISSUE TITLE
Can't find anything using Jackett

### ISSUE THREAD

**Issue by OldMike** [nosmokingbandit/Watcher3#6]
It's okay with Usenet providers but not at all with Bittorrent ones, using Jackett.

Here is what Jacketts log showing:
```Found 0 releases from T411 for: zootopia2016```
Does this mean it searches for "movieyear" and not "movie year"?

**Comment by nosmokingbandit** [comment]
Jackett searches are working fine for me. Jackett's log seems to report the term incorrectly, but in your Watcher logs you'll see what is actually sent .

INFO 2017-03-30 14:06:54,810 root.search_newznab: SEARCHING: http://127.0.0.1:9117/torznab/thepiratebay/api?apikey=APIKEY&t=search&cat=2000&q=night%2Bof%2Bthe%2Bliving%2Bdead%2B1968

**Comment by OldMike** [comment]
OK, still dont understand. Nice work, Watcher is a really light and modern tool but I'll fall back to Radarr or Couchpotato as they work with Jackett the torrents.

Watcher3 logs
```
DEBUG 2017-03-31 05:04:14,847 lib.requests.packages.urllib3.connectionpool._make_request: http://xxx:xx "GET /torznab/xthor/api?apikey=yyy&q=rogue%2Bone%2Ba%2Bstar%2Bwars%2Bstory%2B2016&t=search&cat=2000 HTTP/1.1" 200 18959
DEBUG 2017-03-31 05:04:14,486 lib.requests.packages.urllib3.connectionpool._new_conn: Starting new HTTP connection (1): xxx
INFO 2017-03-31 05:04:14,485 root.search_newznab: SEARCHING: http://xxx:xx/torznab/xthor/api?apikey=APIKEY&q=rogue%2Bone%2Ba%2Bstar%2Bwars%2Bstory%2B2016&t=search&cat=2000
INFO 2017-03-31 05:04:14,484 core.providers.torrent.search_all: http://xxx:xx/torznab/xthor/ does not support imdbid search, using q=rogue+one+a+star+wars+story+2016
INFO 2017-03-31 05:04:13,989 core.sqldb.write: Writing data to CAPS.
DEBUG 2017-03-31 05:04:13,988 lib.requests.packages.urllib3.connectionpool._make_request: http://xxx:xx "GET /torznab/xthor/?t=caps HTTP/1.1" 200 1866
DEBUG 2017-03-31 05:04:13,987 lib.requests.packages.urllib3.connectionpool._new_conn: Starting new HTTP connection (1): xxx
INFO 2017-03-31 05:04:13,985 core.sqldb.torznab_caps: Retreiving caps for http://xxx:xx/torznab/xthor/
lib.requests.exceptions.ReadTimeout: HTTPConnectionPool(host='xxx', port=xx): Read timed out. (read timeout=30)
```

Jackett:
```
Found 14 releases from Xthor for: rogueoneastarwarsstory2016
```

**Comment by nosmokingbandit** [comment]
> Read timed out. (read timeout=30)

Your torrent indexer didn't respond within 30 seconds. There isn't much I can do about that.
