### ISSUE TITLE
Watcher not assigning label to deluge

### ISSUE THREAD

**Issue by ubjeckle** [nosmokingbandit/Watcher3#61]
As per the issue with rTorrent , with deluge it adds the torrent but never adds a label to it. This always goes in as a No Label torrent. I have tried both on web-ui and also daemon protocol but still doesn't add the label. Any help would be much appreciated.

**Comment by nosmokingbandit** [comment]
Since Deluge labels don't affect post-processing it doesn't set the actual label, but instead appends the category to the download dir. So if your download directory is `/users/ubjeckle/downloads/` and your download category is `Watcher` it will set the download dir to `/users/ubjeckle/downloads/Watcher`.

The way the label plugin works is kind of a pain so I never bothered with it. I'll put it on my todo list.

**Comment by nosmokingbandit** [comment]
441fcfa37785a9665fe616dfc674ce589d8268d8 and eb433ac0c7ebac90173ab79de320336e858fd514 should take care of this. I tested both on my server and everything worked fine, but I'll leave this open until you report back.

**Comment by ubjeckle** [comment]
INFO 2017-06-14 15:02:26,328 core.snatcher.snatch_torrent: Successfully sent Casper 1995 BRRip x264 720p-NPW to DelugeWeb.
AttributeError: 'NoneType' object has no attribute 'lower'
    'params': [torrent.lower(), label],
  File "/home/media/watcher3/core/downloaders/deluge.py", line 320, in _set_label
Traceback (most recent call last):
ERROR 2017-06-14 15:02:26,328 core.downloaders.deluge._set_label: Delugeweb set_torrent.
lib.requests.exceptions.MissingSchema: Invalid URL '/tmp/delugeweb-d8xEee/Casper 1995 BRRip x264 720p-NPW.torrent': No schema supplied. Perhaps you meant http:///tmp/delugeweb-d8xEee/Casper 1995 BRRip x264 720p-NPW.torrent?
    raise MissingSchema(error)
  File "/home/media/watcher3/lib/requests/models.py", line 382, in prepare_url
    self.prepare_url(url, params)
  File "/home/media/watcher3/lib/requests/models.py", line 302, in prepare
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/media/watcher3/lib/requests/sessions.py", line 415, in prepare_request
    prep = self.prepare_request(req)
  File "/home/media/watcher3/lib/requests/sessions.py", line 483, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/media/watcher3/lib/requests/api.py", line 58, in request
    return request('get', url, params=params, **kwargs)
  File "/home/media/watcher3/lib/requests/api.py", line 72, in get
    r = requests.get(url, **kwargs)
  File "/home/media/watcher3/core/helpers.py", line 77, in open
    r = Url.open(url, stream=True).content
  File "/home/media/watcher3/core/helpers.py", line 128, in get_hash
Traceback (most recent call last):
ERROR 2017-06-14 15:02:26,245 root.get_hash: Unable to get torrent hash
INFO 2017-06-14 15:02:26,142 core.snatcher.snatch_torrent: Sending torrent to DelugeWeb.



that was taken from the logs

**Comment by nosmokingbandit** [comment]
I'm willing to bet that Deluge isn't on the same machine as Watcher?

Either way, d2ae9db should get you back in business. Deluge downloads a temporary copy of the torrent file before loading it and this was set to overwrite the torrent url so Watcher isn't able to get to the torrent file if it has a link to a file on another computer.
