### ISSUE TITLE
Can't start the new W3 (Python 3.6 + pywin32 for py 3.6 installd)

### ISSUE THREAD

**Issue by D3ltorohd** [nosmokingbandit/Watcher3#63]
Hello,
i will try the new watcher3. But i cant get it run. Installed python 3.6 + pywin32 for py 3.6. On the setup i checked the field that the setup set the path in windows.

Is there a log, where i can find maybe something ?

Python 2.7.13 is also installed.

Greet's

**Comment by PotatoQuality** [comment]
in the map logs you find the log files 👍

**Comment by D3ltorohd** [comment]
hm i cant find anything, no folder no log files. im looking on program data and app data but nothing found.

i have create a .bat file with the following lines.. But it will not work. I need to tell him he should start it with python 3.

cd C:\Watcher3
start python3 watcher.py
