### ISSUE TITLE
Watcher dont find some movies but they still there on the indexer's.

### ISSUE THREAD

**Issue by D3ltorohd** [nosmokingbandit/Watcher3#64]
Hello,
i have a problem. I test watcher and search for a movie, but he found nothing. When i go to the website from my indexers there i find the movie with some qualitys there. But watcher didnt.

What can be the problem ? Some logs are helpfull ?

I have noticed that on of my 3 indexer dont connect. But when i try it with another tool it works fine.

Greet's

**Comment by nosmokingbandit** [comment]
Try something that doesn't work, then make a copy of your log. Email it to `watchernzb@gmail.com` and I'll take a look at it.

**Comment by nosmokingbandit** [comment]
The log indicates that the connection to wizznab is timing out. If it takes more than 30 seconds to get a response back from the indexer.

Try putting this in your browser and see how long it takes to load the page:
https://wizznab.tk/api?apikey=**YOUR API KEY**&t=search&id=tt0063350

**Comment by nosmokingbandit** [comment]
Closing due to age. If this still needs attention feel free to post again.
