### ISSUE TITLE
Movies without poster show up strange in layout.

### ISSUE THREAD

**Issue by ItsMeMike** [nosmokingbandit/Watcher3#66]
![image](https://user-images.githubusercontent.com/7621845/27099279-ba7057c4-507a-11e7-9ccb-8212a1ff9adb.png)
![image](https://user-images.githubusercontent.com/7621845/27099295-c484cde4-507a-11e7-916d-829f33bb1bf9.png)

It is trying to load something that just isn't there.

**Comment by nosmokingbandit** [comment]
It is trying to load the missing poster image, which is copied to the poster directory when adding the movie.

Try removing/adding the movie and see if it loads. If not the log from when the movie is added should tell me what is happening.

**Comment by ItsMeMike** [comment]
I have re-added the movie. Same thing. It is tt5052474

**Comment by nosmokingbandit** [comment]
Hmmm.

Check in `watcher/static/images/` and confirm that `missing_poster.jpg` exists, then look in `watcher/static/images/posters` and check if `tt5052474.jpg` exists.

If they are both there we'll need to see what the browser is trying to do. Open a page with the missing image and press F12 to open the console (this is the button for Chrome, Firefox, Edge, and probably Safari). You should see a line in red that says the image didn't load. It should look like:

```
GET 
http://localhost:9090/watcher/static/images/posters/not_an_image.jpg [HTTP/1.1 404 Not Found 3ms]
```
        

Either copy this text or email me a screenshot of it `watchernzb@gmail.com`

**Comment by ItsMeMike** [comment]
missing_poster.jpg exists. I did have an empty file for ttxxxx.jpg. I deleted one and refreshed metadata.
This resulted in the following error in the logs:
```
ERROR 2017-06-19 09:45:01,974 core.library.save_poster: Poster save_poster get
Traceback (most recent call last):
  File "C:\Watcher3\core\library.py", line 950, in save_poster
    poster_bytes = Url.open(poster_url, stream=True).content
  File "C:\Watcher3\core\helpers.py", line 77, in open
    r = requests.get(url, **kwargs)
  File "C:\Watcher3\lib\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Watcher3\lib\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Watcher3\lib\requests\sessions.py", line 497, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Watcher3\lib\requests\sessions.py", line 612, in send
    adapter = self.get_adapter(url=request.url)
  File "C:\Watcher3\lib\requests\sessions.py", line 695, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
lib.requests.exceptions.InvalidSchema: No connection adapters were found for 'C:\Watcher3/static/images/missing_poster.jpg'
ERROR 2017-06-19 09:45:02,034 core.library.save_poster: Unable to save poster to disk.
Traceback (most recent call last):
  File "C:\Watcher3\core\library.py", line 958, in save_poster
    output.write(poster_bytes)
UnboundLocalError: local variable 'poster_bytes' referenced before assignment
INFO 2017-06-19 09:45:02,035 core.library.save_poster: Poster saved to static/images/posters/tt1630029.jpg
```

I hope it helps!

**Comment by nosmokingbandit** [comment]
I'm not 100% sure why it isn't working. Well, I *know* why it isn't working, I just don't know how it gets to that point.

Do you have a webroot path enabled and what is it?

While I was poking around I simplified the whole process a little. I doubt it, but commit 9aedeefd8cc38c2cc39715f98521cd86bf4ce845 might fix it.

**Comment by ItsMeMike** [comment]
No custom webroot enabled. Running on host 0.0.0.0:8082, without proxy.

**Comment by ItsMeMike** [comment]
Not sure what changed, it seemed okay for a while. I added some movies to my IMDB watchlist yesterday and today I login and see that 21 movies were missing posters (same problem as before; not the missing_poster.jpg).

Manually updating the metadata seems to fix it. But I am unsure for how long.
After a couple of movies this started bugging out as well and I got a server error:
'''
DEBUG 2017-06-27 17:41:49,387 core.sqldb.get_search_results: Retrieving Search Results for tt2557478.
INFO 2017-06-27 17:41:50,403 core.library.update: Updating metadata for tt2557478
DEBUG 2017-06-27 17:41:50,404 core.sqldb.get_movie_details: Retrieving details for tt2557478.
INFO 2017-06-27 17:41:50,405 core.movieinfo._search_tmdbid: Searching TMDB https://api.themoviedb.org/3/movie/268896?language=en-US&append_to_response=alternative_titles,external_ids,release_dates
WARNING 2017-06-27 17:41:50,897 core.movieinfo._search_tmdbid: Unable to reach TMDB, error 401
WARNING 2017-06-27 17:41:50,897 core.library.update: Empty response from TMDB.
ERROR 2017-06-27 17:41:50,897 cherrypy.error.1871907726448.error: [27/Jun/2017:17:41:50] HTTP 
Traceback (most recent call last):
  File "C:\Watcher3\lib\cherrypy\_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "C:\Watcher3\lib\cherrypy\lib\encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "C:\Watcher3\lib\cherrypy\lib\jsontools.py", line 61, in json_handler
    value = cherrypy.serving.request._json_inner_handler(*args, **kwargs)
  File "C:\Watcher3\lib\cherrypy\_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "C:\Watcher3\core\ajax.py", line 712, in update_metadata
    if r['response'] is True:
TypeError: 'NoneType' object is not subscriptable
INFO 2017-06-27 17:41:50,897 cherrypy.error.1871907726448.error: [27/Jun/2017:17:41:50] HTTP 
Request Headers:
  Remote-Addr: 127.0.0.1
  HOST: localhost:8082
  CONNECTION: keep-alive
  PRAGMA: no-cache
  CACHE-CONTROL: no-cache
  ORIGIN: http://localhost:8082
  USER-AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
  ACCEPT: */*
  X-REQUESTED-WITH: XMLHttpRequest
  DNT: 1
  REFERER: http://localhost:8082/
  ACCEPT-ENCODING: gzip, deflate, br
  ACCEPT-LANGUAGE: nl,en-US;q=0.8,en;q=0.6,ja;q=0.4,de;q=0.2
  COOKIE: list_style=posters; list_direction=asc; session=66b38f67eaf29de0fbe3d3125a5edd5dd2b62dee
  Content-Type: application/x-www-form-urlencoded; charset=UTF-8
  Content-Length: 30
'''
Perhaps this is what happened overnight as well?

**Comment by nosmokingbandit** [comment]
There was a bug that I fixed in 4fee259d5b653d51722414a6529a860b85c1e6ee.
You can manually get the posters back like you did, or wait until the next mass metadata update (runs every 72 hours) and they should be re-downloaded.

**Comment by jaketame** [comment]
@nosmokingbandit This commit hasn't solved the issue, css is still misaligned, posters are 300px high but col-md-3 has height auto thus causes issues.

Simple fix to add fixed height to the image poster size. I've made a pull request.

**Comment by nosmokingbandit** [comment]
Closing due to age. If this still needs attention feel free to post again.
