### ISSUE TITLE
Plex import

### ISSUE THREAD

**Issue by j0hnsen** [nosmokingbandit/Watcher3#67]
Hi,
I try to import ~5.5k Movies with an csv exported from plex (from your guide) but every time it says "Unable to parse CSV file."

Log shows this:

ERROR 2017-06-15 20:26:52,144 core.library.read_csv: Error parsing Plex CSV.
Traceback (most recent call last):
  File "/root/watcher/core/library.py", line 298, in read_csv
    width = int(movie['Width'])
ValueError: invalid literal for int() with base 10: 'N/A'

**Comment by nosmokingbandit** [comment]
Ah. I assumed plex would always know the width of the video, but that doesn't seem to be the case.

**Comment by nosmokingbandit** [comment]
b305a92bb7b33294db6a3691912d07e3b2cec4ee takes care of that problem. If Plex doesn't supply the movie width you will be asked to supply it instead.

There may be other fields that Plex leaves as N/A, but I haven't found any. I don't use Plex so I only added a few dozen movies to test with and none of them seem to have problems.

**Comment by j0hnsen** [comment]
Still have massiv problems...

DEBUG 2017-06-18 00:41:02,400 core.library.read_csv: 10 Years width expressed as N/A, unable to parse resolution.
DEBUG 2017-06-18 00:41:02,400 core.library.read_csv: 11:14 width expressed as 1280 - 576, unable to parse resolution.
ERROR 2017-06-18 00:41:02,400 core.library.read_csv: Error parsing Plex CSV.
Traceback (most recent call last):
  File "/root/watcher/core/library.py", line 312, in read_csv
    parsed['size'] = int(movie['Part Size as Bytes'])
ValueError: invalid literal for int() with base 10: '4695544036 - 724213760'

**Comment by jaketame** [comment]
This is when there are duplicate movie files, the export plugin groups them together rather than separate lines so you will see multiple entry's per column.

**Comment by nosmokingbandit** [comment]
"Massive" problems....

I submitted an issue to https://github.com/ukdtom/ExportTools.bundle to see if the dev wants to give a more sane format for duplicate titles. Until I hear back I'm not going to rewrite my parser.

You can always manually add the movies that can't be parsed.

**Comment by nosmokingbandit** [comment]
@j0hnsen, @jaketame 
I just pushed ed96db2533ab82d1b73e2634b5116e0bb2fc6a98, which may or may not help with this. It is an ugly patch that I'm not super thrilled about, but it may work well enough until I do something through Plex's api (which is clunky and not documented well at all), ExportTools exports predictable tables, or I figure out something else entirely.

Please report back either way.

**Comment by nosmokingbandit** [comment]
Closing due to age. If this still needs attention feel free to post again.
