### ISSUE TITLE
Creating/altering the project wiki pages

### ISSUE THREAD

**Issue by kaibosh** [nosmokingbandit/Watcher3#68]
I'd like to help out a little with the wiki, perhaps starting with a table of contents for the home page.

However, the new/edit buttons are not showing up. Could this be enabled in the github settings?

**Comment by nosmokingbandit** [comment]
Sure. I forgot to allow public editing when we moved to this repo. Everything should be fully editable now, so go nuts. If you need any info from me feel free to ask.

**Comment by kaibosh** [comment]
Great thanks, it's now open and I've made a start. :)
