### ISSUE TITLE
core.downloaders.deluge.add_torrent: Unable to send magnet.

### ISSUE THREAD

**Issue by bbrendon** [nosmokingbandit/Watcher3#69]
I'm getting this when I click the "Download" button.

```
INFO 2017-06-16 23:41:59,798 core.snatcher.snatch_torrent: Sending magnet to DelugeRPC.
ERROR 2017-06-16 23:42:05,081 core.downloaders.deluge.add_torrent: Unable to send magnet.
Traceback (most recent call last):
  File "/u0/opt/watcher3/core/downloaders/deluge.py", line 92, in add_torrent
    download_id = client.call('core.add_torrent_magnet', torrent['torrentfile'], options).decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'
```

I'm pretty sure I'm on the latest watcher3. Running python 3.4.2

**Comment by nosmokingbandit** [comment]
That indicates that something didn't work on Deluge's side. It is working fine on my testing server, so I'll need a bit more from you.

Try setting deluge to [log to a file](http://dev.deluge-torrent.org/wiki/Troubleshooting#EnableDelugeLogging), then immediately after starting deluge try to add a magnet through watcher, then immediately make a copy of the log (so it isn't filled with lines that don't help us).

You can email me that log then if you want. `watchernzb@gmail.com` I'll see what I can figure out.

**Comment by nosmokingbandit** [comment]
Closing due to age. If this still needs attention feel free to post again.
