### ISSUE TITLE
Importing issue

### ISSUE THREAD

**Issue by WilliamJBrown** [nosmokingbandit/Watcher3#7]
`TypeError: object of type 'bool' has no len()
    length = len(movie_data) + len(corrected_movies)
  File "/opt/watcher3/app/core/ajax.py", line 699, in submit_import
    for chunk in body:
  File "/opt/watcher3/app/lib/cherrypy/lib/encoding.py", line 100, in encoder
    return next(self.iter_response)
  File "/opt/watcher3/app/lib/cherrypy/_cpwsgi.py", line 286, in __next__
    return func(*args, **kwargs)
  File "/opt/watcher3/app/lib/cherrypy/_cpwsgi.py", line 189, in trap`

I can import individual files but when i add the full lot of movies (500~) it throws a 500 internal error. 

Will send an email with full logs.

**Comment by nosmokingbandit** [comment]
I've got a fix for this, but I need to test a bunch of other stuff before I
push it out. I'm adding more import options, so too much is changing to
just fix this one thing. Hang loose for a bit.

**Comment by nosmokingbandit** [comment]
I definitely forgot to let you know that this should be fixed as of 795c0fcbe8ffc4d270f2f0a9b65ceaad308bbfc7, is everything ok on your end?
