### ISSUE TITLE
Unable to reach TMDB

### ISSUE THREAD

**Issue by WilliamJBrown** [nosmokingbandit/Watcher3#72]
Seems that sometimes when I search for a movie it fails. So often I have to search 2 or 3 times before I can get results. I can see the logs are failing so just wanted you to be aware. 

Not a biggie, just so you know. :)

**Comment by nosmokingbandit** [comment]
TheMovieDB disabled one of my api keys. Just pushed an update to fix it.

**Comment by WilliamJBrown** [comment]
Wow you are quick, thanks so much.

**Comment by WilliamJBrown** [comment]
Looks good!

**Comment by nosmokingbandit** [comment]
It was an easy fix. And if I'm being completely transparent, when I see a notification from certain people (like you) I read it right away rather than wait until tomorrow. It pays to stick around since the beginning :D
