### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#73]
I'm running watcher in Docker with a webroot path, when the login required is selected I get a redirect loop back to the login page.

I open up the browser url of  ****/watcher
Login - Receive success login via log
Login page still displayed.

'''
INFO 2017-06-27 07:25:53,940 core.auth.on_login: Successful login from ***
'''

**Comment by nosmokingbandit** [comment]
There was a bug where it wouldn't redirect to the main page if there was a trailing slash in the window location, so df359bda3cf8d9d86d6477cf5c6a35a44b618cca might fix this for you.

**Comment by jaketame** [comment]
So running the latest however web login doesn't work but mobile login does :-\

**Comment by WilliamJBrown** [comment]
I had this issue, I did a fresh install and everything seemed to work. Might have been something with updates. Give a fresh install a try and see if that helps

**Comment by nosmokingbandit** [comment]
Despite all my efforts I can't make the login fail. Which is weird because I usually have the opposite problem.

Try clearing your browser's cookies and restarting Watcher.

**Comment by jaketame** [comment]
Now resolved after cleaning cache + cookies. Thanks!

**Comment by nosmokingbandit** [comment]
Awesome. Let me know if it ever acts stupid again.
