### ISSUE TITLE
Click Here to view changes issue

### ISSUE THREAD

**Issue by WilliamJBrown** [nosmokingbandit/Watcher3#76]
Another small one for you, not a biggie. 

When I click on here to view new changes it just opens another watcher tab for me. 

Pretty simple stuff. Have a good one!

**Comment by nosmokingbandit** [comment]
Got it in https://github.com/nosmokingbandit/Watcher3/commit/02a4bcf1db043fb16b9412bfd5a3541447cf28bc

You won't see that until the next update cycle, so I'll just close this for now. Let me know if the problem persists next time and update come through.
