### ISSUE TITLE
Creating hardlink? 

### ISSUE THREAD

**Issue by WilliamJBrown** [nosmokingbandit/Watcher3#77]
I get a error when moving the files. It seems to be an error with hardlink when I have move set as the setting in post processing. 

https://pastebin.com/h4zFPHdq

https://gyazo.com/8cc41f7a3b91a356928c732a4fe9119f

**Comment by nosmokingbandit** [comment]
I was about to type out an explanation, but I already did -- read the commit notes.

Commit abe8bd5058797fcff2ae824f0232ad3f66bc92bc.

I never have cleanup enabled on my test server because I don't want to delete my test copies of movies. Didn't work so well for me this time.

**Comment by WilliamJBrown** [comment]
Works good!

**Comment by WilliamJBrown** [comment]
Must have not been at 100% scale for chrome. at 100% it looks normal. It scales different at other percentages. 

https://gyazo.com/c8a00689428f7fecf969a9931995bdfe

Is mine at 100%

**Comment by nosmokingbandit** [comment]
That makes me feel better, thanks.

Only 100% scale screenshots from now on.
