### ISSUE TITLE
Directory import malfunction? 

### ISSUE THREAD

**Issue by WilliamJBrown** [nosmokingbandit/Watcher3#78]
https://pastebin.com/7rcQ71U7

Is the full log

https://pastebin.com/pJ5PbYGt

Here is the movies that get found in import. Only a few movies are actually are able to be imported. Seems like it gets stuck or doesn't recognize the other movies. They are all smaller movies sub 5GB. Most movies I have are 15ish. So it finds the directory but just can't seem to get put into the list for import. 

Hard to explain but the directory import is acting weird. Not sure if you can make sense. 

let me know if you need anything. :)

**Comment by nosmokingbandit** [comment]
What file format are the movies? I recently added a mimetype check to make sure non-movie files are ignored.

You should have a section on the log with a lot of lines that with `._walk` in them with files listed. Can you get that section for me?

**Comment by WilliamJBrown** [comment]
The containers are MKV. In the same folder as the movies I have subtitle files .srt files. In the first paste bin if you go down you should see the walk section. Starts line 81 and down.

**Comment by WilliamJBrown** [comment]
Looks like its only picking up MP4 files.

**Comment by nosmokingbandit** [comment]
I removed the mimetype filter 1fbcb357dc182e40cc2216a16257b48e4d20ecb6, did
it make a difference for you?

**Comment by WilliamJBrown** [comment]
I just tried importing today and got a new error. Again gibberish to me. 

Hope you can decipher this :)

https://pastebin.com/FfmFtFSA

**Comment by WilliamJBrown** [comment]
Just tested works well! :D
