### ISSUE TITLE
Import directory failure

### ISSUE THREAD

**Issue by mpalpha** [nosmokingbandit/Watcher3#79]
I get the following page when I choose "directory" on the import page.

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/watcher/lib/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/watcher/lib/cherrypy/lib/encoding.py", line 220, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/watcher/lib/cherrypy/_cpdispatch.py", line 60, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/watcher/core/app.py", line 88, in library
    file_list = [i for i in os.listdir(home) if os.path.isdir(os.path.join(home, i)) and not i.startswith('.')]
PermissionError: [Errno 13] Permission denied: '/root'

**Comment by WilliamJBrown** [comment]
PermissionError: [Errno 13] Permission denied: '/root' looks like it doesn't have the right permissions?

**Comment by nosmokingbandit** [comment]
This is coming from attempting to read the directory for the Web UI's file browser. It tries to read the user's home folder, which the user should have permission to access, so there might be weird permission problems in the user directories.

I'll add a failsafe that loads the Watcher directory instead, but Watcher will still need permission for any folder containing movies to import.

**Comment by nosmokingbandit** [comment]
Closing due to age. If this still needs attention feel free to post again.

**Comment by mpalpha** [comment]
the fallback fixed it.
