### ISSUE TITLE
black hole for torrent files

### ISSUE THREAD

**Issue by turbalf** [nosmokingbandit/Watcher3#80]
Hello,
I try to leave CP and watcher seems to be very nice (radarr don't manage iso files...) but I use black hole and sync app to send torrent to my seedbox.
Is there a hope to see black hole feature come in watcher please ?
Thanks

**Comment by nosmokingbandit** [comment]
Added in 37d83e9175a8c80e67460c23bd0c79a7ed079636

It isn't perfectly reliable for magnet links since it has to go through a caching site (like itorrents). If none of the caching sites have the torrent file it won't be able to save it locally.

**Comment by nosmokingbandit** [comment]
Closing due to age. If this still needs attention feel free to post again.
