### ISSUE TITLE
Mobile CSS issue

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#83]
Using on iPhone and the Light theme. The links under the drop down menus for Library and Settings are invisible.

**Comment by jaketame** [comment]
Looks like the isn't applying a different font-color, so background and text are the same colour. Upon looking at Less.css there doesn't appear to be a setting for @media (max-width: 768px) to cover small devices.

@media (max-width: 768px)
Light.css?v=06.28:1
.navbar-nav .open .dropdown-menu>li>a {
    padding: .25em 1em;
    line-height: 1.25em;
}

**Comment by nosmokingbandit** [comment]
https://github.com/nosmokingbandit/Watcher3/commit/3f0280360ef893354bdf7e6f3a9adffb804c8e1a fixes this. Bootstrap is both wonderful and frustrating. Some things are insanely easy, but working with a good chunk of someone else's code is always a bit more difficult than I'd like.

**Comment by jaketame** [comment]
All resolved, nice one.
