### ISSUE TITLE
Library - Sorting Incorrectly

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#84]
Version: Latest

I'm sorting via Status in Desc order to display undownloaded items first however there are a few items that are showing up as Finished before the Snatched/Wanted items.

Finished ***** 2013
Finished ***** 2017
Finished *****  2017
Finished *****  2017
Snatched ***** 2008
Snatched *****  2017
Wanted *****  2017
Waiting *****  2017
Waiting *****  2017

**Comment by nosmokingbandit** [comment]
That is working as indented. I have it set up so that the status is sorted chronologically, being Waiting > Wanted > Found > Snatched > Finished.

I can easily tweak that easily enough, but that is what made the most sense when I created the sort method.

**Comment by jaketame** [comment]
Sorry maybe I didn't explain it correctly

Finished is showing up before Waiting at the top and then again after Snatched. I will screenshot it.

**Comment by jaketame** [comment]
here we go 
http://imgur.com/a/Vc7Rt

**Comment by nosmokingbandit** [comment]
Your screenshot didn't help, but I got what you mean.

899cd1b7a6bce4fbbb214a140176e68ac77671b0 will make all Finished movies stay together.

**Comment by jaketame** [comment]
Looks resolved now thanks
