### ISSUE TITLE
Postprocessing

### ISSUE THREAD

**Issue by WilliamJBrown** [nosmokingbandit/Watcher3#86]
Ever since a few updates back post processing doesn't seem to be working. 
Cant make light of what is happening. 

Let me know if you need anything. 

See logs: 

https://pastebin.com/NzMambNq

**Comment by nosmokingbandit** [comment]
It was a combination of handling an obfuscated file name and trying to find that title on theMovieDatabase.

With 7c8b89ada7ea1111fe3d2d13e1f275c15eff31db I tested a processing request of `/Night of the Living Dead/2bd3dea733ebd782870a68468f0ac6ae.mkv` (the file name that caused your problem) and it worked fine for me. Let me know if you run into more trouble.
