### ISSUE TITLE
Movie Popup changes

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#89]
I feel the size of the movie popup could be changed slighty

Proposed changes

# Decrease poster size, fits nicer on screen
@media (min-width: 768px)
Light.css?v=07.10:1
.col-md-4 {
    float: left;
    width: 25.33333333%;

# Decrease group button sizes
    .btn-group-justified {
    display: table;
    width: 33%;
    table-layout: fixed;
    border-collapse: separate;

# Decrease font size for plot
@media (min-width: 992px)
status.css?v=06.28:222
div.modal-body p.plot {
    min-height: 8em;
    font-size: 14px;
}

Also can we move the Quality/Status/Save button nice to the small group buttons?

**Comment by nosmokingbandit** [comment]
Can you submit this as a Pull Request? That makes it much easier for me to
compare and merge.

I see from the changes what you are going for, but the changes should be
made to the markup when possible. For example, changing the poster div to a
`col-md-3` sets the width to 25%, then we can set the adjacent div to a
`col-md-9` to take up the rest of the space.

I'll try to get the quality/status/save buttons in the top row as well, but
that gets a little trickier to make everything work on all resolutions.

**Comment by jaketame** [comment]
Nice changes so far, created a pull request for some more minor tweaks. Aim is to try and get more viewing space for the search results as I feel its too cramp.

**Comment by jaketame** [comment]
Thanks for the merge. Looks much neater on both web and mobile.
