### ISSUE TITLE
nzbget.py failed but was successful within Watcher

### ISSUE THREAD

**Issue by jaketame** [nosmokingbandit/Watcher3#90]
NZBGet reported a pp-failure however Watcher actually executed and imported the movie correctly.

NZBGet Log;
Wed Jul 12 2017 15:19:08 | Post-process-script nzbget.py for ******* failed (terminated with unknown status)
INFO | Wed Jul 12 2017 15:19:08 | nzbget: AttributeError: 'unicode' object has no attribute 'get'
INFO | Wed Jul 12 2017 15:19:08 | nzbget: if response.get('status') == 'finished':
INFO | Wed Jul 12 2017 15:19:08 | nzbget: File "/config/scripts/nzbget.py", line 74, in <module>
INFO | Wed Jul 12 2017 15:19:08 | nzbget: Traceback (most recent call last):
INFO | Wed Jul 12 2017 15:18:19 | nzbget: Sending ****** to Watcher as Complete.

Watcher;
INFO 2017-07-12 15:19:08,558 core.postprocessing.POST: Post-processing complete.
#################################
***REMOVED ****
#################################
INFO 2017-07-12 15:18:19,511 core.postprocessing.POST: Post-processing request received.
#################################

**Comment by jaketame** [comment]
Raised for awareness, nzbget.py from Watcher requires Python3.4+ (known bug in 2), Docker NZBget comes with Python2.7

**Comment by nosmokingbandit** [comment]
I think this was actually from me double-encoding the output in post-processing.
35215fda3fe33633a86a5fdf98a757f13417f5e2 should return the ability for the scripts to work independent of python version.

I'm not sure why 3 worked. The json-decoder in 3.X might be smarter than 2.X.
