### ISSUE TITLE
Missing css on Landing page 

### ISSUE THREAD

**Issue by BillVeusees** [nosmokingbandit/Watcher3#96]
Hi, 
It s been a few weeks that watcher's landing page (login page) is missing css and elements as it shows a logo slightly on the right and two login fields on the bottom left over a full blank page.

I tried to pull manually and refresh cache, but it does not resolve the problem.

Is it a problem on my side ?

Thanks

**Comment by nosmokingbandit** [comment]
Might be on your side. Open the page and press F12, go to the Console tab and let me know if there are any error messages.

**Comment by BillVeusees** [comment]
i have got a 404 on /auth/static/css/themes/.css?v=06.02 

`        <title>Watcher</title>
        <meta content="" name="url_base">
        <meta content="width=device-width,initial-scale=1" name="viewport">
        <link href="/auth/static/css/themes/.css?v=06.02" rel="stylesheet">
        <link href="/auth/static/css/lib/materialdesignicons.min.css?v=06.02" rel="stylesheet">
        <link href="/auth/static/css/login.css?v=06.02" rel="stylesheet">
        <script src="/auth/static/js/lib/jquery.310.min.js?v=06.14" type="text/javascript"></script>
        <script src="/auth/static/js/login.js?v=06.27" type="text/javascript"></script>
        <link href="/auth/static/css/style.css?v=06.07" rel="stylesheet">
        <meta name="enable_notifs" content="false">`

**Comment by nosmokingbandit** [comment]
Does the Default css load on other pages?

**Comment by BillVeusees** [comment]
Yes the login page was the only affected

**Comment by nosmokingbandit** [comment]
4fef6c5 should take care of that. I'm not 100% sure what happened, but this fix uses the Default theme as the fallback like the rest of the pages.

**Comment by BillVeusees** [comment]
Thanks a lot
